-- Migration: confirmed watch reports (wizard table)
-- Safe to re-run

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'wizard'
  ) THEN
    CREATE TABLE public.wizard (
      id bigint generated by default as identity not null,
      timestamp timestamp with time zone not null default now(),
      agency_type text[] null,
      agency_other text null,
      location jsonb null,
      media_url text null,
      officer_moving boolean null,
      officer_direction text null,
      lights_on boolean null,
      sirens_on boolean null,
      submitted_by uuid null,
      test boolean null default false,
      constraint wizard_pkey primary key (id)
    ) TABLESPACE pg_default;
  END IF;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_wizard_test ON public.wizard USING btree (test) TABLESPACE pg_default;
