-- Migration: Add auto-incrementing numeric id to missing_person_records
-- Date: 2025-11-03
-- Safe to run multiple times.

-- Add the identity column if it does not exist
ALTER TABLE public.missing_person_records
  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Backfill any NULL ids on existing rows (if any)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'missing_person_records' AND column_name = 'id'
  ) THEN
    -- Assign ids to rows that don't have one yet
    EXECUTE 'UPDATE public.missing_person_records
             SET id = COALESCE(id, nextval(pg_get_serial_sequence(''public.missing_person_records'',''id'')))
             WHERE id IS NULL';
  END IF;
END $$;

-- Ensure uniqueness and fast ordering by the new id
CREATE UNIQUE INDEX IF NOT EXISTS idx_missing_person_records_id ON public.missing_person_records (id);

-- Optionally enforce NOT NULL once backfilled
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'missing_person_records' AND column_name = 'id'
  ) THEN
    BEGIN
      ALTER TABLE public.missing_person_records ALTER COLUMN id SET NOT NULL;
    EXCEPTION WHEN others THEN
      -- ignore if constraint already set or blocked by existing nulls
      NULL;
    END;
  END IF;
END $$;

