// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-academy-mdx-manifest.mjs
/* eslint-disable */

import type { ReactElement } from 'react';
import type { AcademyCourseFrontmatter } from '@workspace/ui/data/academy/types';

const mod_dispatch_coordination = () => import('@workspace/ui/data/academy/courses/Advanced_Tools/dispatch-coordination.mdx');
const mod_heatmap_verification = () => import('@workspace/ui/data/academy/courses/Advanced_Tools/heatmap-verification.mdx');
const mod_report_reviewing = () => import('@workspace/ui/data/academy/courses/Advanced_Tools/report-reviewing.mdx');
const mod_conflict_repair = () => import('@workspace/ui/data/academy/courses/Community_Care___and___Emotional_Support/conflict-repair.mdx');
const mod_mutual_aid_health_wellness = () => import('@workspace/ui/data/academy/courses/Community_Care___and___Emotional_Support/mutual-aid-health-wellness.mdx');
const mod_peer_support_checkins = () => import('@workspace/ui/data/academy/courses/Community_Care___and___Emotional_Support/peer-support-checkins.mdx');
const mod_bystander_support = () => import('@workspace/ui/data/academy/courses/Community_Safety___and___Rights/bystander-support.mdx');
const mod_interacting_with_law_enforcement = () => import('@workspace/ui/data/academy/courses/Community_Safety___and___Rights/interacting-with-law-enforcement.mdx');
const mod_court_support = () => import('@workspace/ui/data/academy/courses/Court___and___Post-Raid_Support/court-support.mdx');
const mod_jail_support_legal_logistics = () => import('@workspace/ui/data/academy/courses/Court___and___Post-Raid_Support/jail-support-legal-logistics.mdx');
const mod_understanding_court_support = () => import('@workspace/ui/data/academy/courses/Court___and___Post-Raid_Support/understanding-court-support.mdx');
const mod_app_free_tactics = () => import('@workspace/ui/data/academy/courses/Direct_Action___and___Protective_Roles/app-free-tactics.mdx');
const mod_checkpoint_monitoring = () => import('@workspace/ui/data/academy/courses/Direct_Action___and___Protective_Roles/checkpoint-monitoring.mdx');
const mod_digital_resilience_contingency_comms = () => import('@workspace/ui/data/academy/courses/Direct_Action___and___Protective_Roles/digital-resilience-contingency-comms.mdx');
const mod_advanced_deescalation = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/advanced-deescalation.mdx');
const mod_care_support = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/care-support.mdx');
const mod_collective_safety_protocols = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/collective-safety-protocols.mdx');
const mod_community_intelligence_situational_reporting = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/community-intelligence-situational-reporting.mdx');
const mod_crisis_debrief_care = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/crisis-debrief-care.mdx');
const mod_deescalation_basics = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/deescalation-basics.mdx');
const mod_environmental_safety = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/environmental-safety.mdx');
const mod_escalation_evacuation_protocols = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/escalation-evacuation-protocols.mdx');
const mod_field_safety = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/field-safety.mdx');
const mod_logistics_resource_management = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/logistics-resource-management.mdx');
const mod_mass_casualty_response = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/mass-casualty-response.mdx');
const mod_medical_basics_field_safety = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/medical-basics-field-safety.mdx');
const mod_national_guard_interactions = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/national-guard-interactions.mdx');
const mod_otg_checklist = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/otg-checklist.mdx');
const mod_rapid_field_assessment_triage = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/rapid-field-assessment-triage.mdx');
const mod_trauma_risk_awareness = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/trauma-risk-awareness.mdx');
const mod_weapon_safety_firearms_101 = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization/weapon-safety-firearms-101.mdx');
const mod_academy_overview = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/academy-overview.mdx');
const mod_art_watch = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/art-watch.mdx');
const mod_data_ethics_pledge = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/data-ethics-pledge.mdx');
const mod_dispatch_training_pathway = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/dispatch-training-pathway.mdx');
const mod_how_to_report = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/how-to-report.mdx');
const mod_signal_basics_accessible = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/signal-basics-accessible.mdx');
const mod_support_art = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/support-art.mdx');
const mod_why_we_do_this = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/why-we-do-this.mdx');
const mod_burner_phones_security_culture = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/burner-phones-security-culture.mdx');
const mod_digital_security_basics = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/digital-security-basics.mdx');
const mod_intro_to_art = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/intro-to-art.mdx');
const mod_kyr_basics = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/kyr-basics.mdx');
const mod_legal_risk_tech = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/legal-risk-tech.mdx');
const mod_media_awareness_volunteers = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/media-awareness-volunteers.mdx');
const mod_mental_health_resilience = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/mental-health-resilience.mdx');
const mod_mesh_networks_intro = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/mesh-networks-intro.mdx');
const mod_myth_of_total_anonymity = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/myth-of-total-anonymity.mdx');
const mod_opsec_101 = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/opsec-101.mdx');
const mod_signal_tips = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/signal-tips.mdx');
const mod_field_role_training_hub = () => import('@workspace/ui/data/academy/courses/Level_2__c___Field_Coordination_Basics___lp__Basic_Dispatcher__rp__/field-role-training-hub.mdx');
const mod_outreach_messaging_community_trust = () => import('@workspace/ui/data/academy/courses/Level_2__c___Field_Coordination_Basics___lp__Basic_Dispatcher__rp__/outreach-messaging-community-trust.mdx');
const mod_responding_to_dispatch_calls = () => import('@workspace/ui/data/academy/courses/Level_2__c___Field_Coordination_Basics___lp__Basic_Dispatcher__rp__/responding-to-dispatch-calls.mdx');
const mod_dealing_with_chaos = () => import('@workspace/ui/data/academy/courses/Level_3__c___Dispatcher_Certification___lp__Verified_Dispatcher__rp__/dealing-with-chaos.mdx');
const mod_trust_and_ethics_in_dispatch = () => import('@workspace/ui/data/academy/courses/Level_3__c___Dispatcher_Certification___lp__Verified_Dispatcher__rp__/trust-and-ethics-in-dispatch.mdx');
const mod_admin_tools = () => import('@workspace/ui/data/academy/courses/Level_4__c___Zone_Lead___lp__Admin_Dispatcher__rp__/admin-tools.mdx');
const mod_cross_zone_coordination = () => import('@workspace/ui/data/academy/courses/Level_4__c___Zone_Lead___lp__Admin_Dispatcher__rp__/cross-zone-coordination.mdx');
const mod_incident_response_admins = () => import('@workspace/ui/data/academy/courses/Level_4__c___Zone_Lead___lp__Admin_Dispatcher__rp__/incident-response-admins.mdx');
const mod_regional_data_stewardship = () => import('@workspace/ui/data/academy/courses/Level_4__c___Zone_Lead___lp__Admin_Dispatcher__rp__/regional-data-stewardship.mdx');
const mod_trust_networks_signature_management = () => import('@workspace/ui/data/academy/courses/Level_4__c___Zone_Lead___lp__Admin_Dispatcher__rp__/trust-networks-signature-management.mdx');
const mod_zone_administration = () => import('@workspace/ui/data/academy/courses/Level_4__c___Zone_Lead___lp__Admin_Dispatcher__rp__/zone-administration.mdx');
const mod_zone_lead_overview = () => import('@workspace/ui/data/academy/courses/Level_4__c___Zone_Lead___lp__Admin_Dispatcher__rp__/zone-lead-overview.mdx');
const mod_60_day_checklist = () => import('@workspace/ui/data/academy/courses/Logistics___and___Mutual_Aid_Operations/60-day-checklist.mdx');
const mod_60_day_preparedness = () => import('@workspace/ui/data/academy/courses/Logistics___and___Mutual_Aid_Operations/60-day-preparedness.mdx');
const mod_advanced_logistics_resource_planning = () => import('@workspace/ui/data/academy/courses/Logistics___and___Mutual_Aid_Operations/advanced-logistics-resource-planning.mdx');
const mod_cdc_location_selection = () => import('@workspace/ui/data/academy/courses/Logistics___and___Mutual_Aid_Operations/cdc-location-selection.mdx');
const mod_cdc_logistics_site_operations = () => import('@workspace/ui/data/academy/courses/Logistics___and___Mutual_Aid_Operations/cdc-logistics-site-operations.mdx');
const mod_logistics_command_coordination = () => import('@workspace/ui/data/academy/courses/Logistics___and___Mutual_Aid_Operations/logistics-command-coordination.mdx');
const mod_supply_chain_resilience = () => import('@workspace/ui/data/academy/courses/Logistics___and___Mutual_Aid_Operations/supply-chain-resilience.mdx');
const mod_cross_regional_ethics = () => import('@workspace/ui/data/academy/courses/Movement_Strategy___and___Ethics/cross-regional-ethics.mdx');
const mod_ethical_dilemmas_direct_action = () => import('@workspace/ui/data/academy/courses/Movement_Strategy___and___Ethics/ethical-dilemmas-direct-action.mdx');
const mod_information_ops_counter_propaganda = () => import('@workspace/ui/data/academy/courses/Movement_Strategy___and___Ethics/information-ops-counter-propaganda.mdx');
const mod_movement_strategy_ethics = () => import('@workspace/ui/data/academy/courses/Movement_Strategy___and___Ethics/movement-strategy-ethics.mdx');
const mod_movement_sustainability_legacy = () => import('@workspace/ui/data/academy/courses/Movement_Strategy___and___Ethics/movement-sustainability-legacy.mdx');
const mod_after_action_data_hygiene = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal/after-action-data-hygiene.mdx');
const mod_documentation_safety = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal/documentation-safety.mdx');
const mod_fourth_amendment_rights = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal/fourth-amendment-rights.mdx');
const mod_legal_followthrough_jail_support = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal/legal-followthrough-jail-support.mdx');
const mod_media_disinformation_handling = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal/media-disinformation-handling.mdx');
const mod_visual_alerts = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal/visual-alerts.mdx');
const mod_community_defense_center = () => import('@workspace/ui/data/academy/courses/Pod_Creation___and___Regional_Readiness/community-defense-center.mdx');
const mod_pod_directory = () => import('@workspace/ui/data/academy/courses/Pod_Creation___and___Regional_Readiness/pod-directory.mdx');
const mod_pod_video_content = () => import('@workspace/ui/data/academy/courses/Pod_Creation___and___Regional_Readiness/pod-video-content.mdx');
const mod_radio_communications = () => import('@workspace/ui/data/academy/courses/Pod_Creation___and___Regional_Readiness/radio-communications.mdx');
const mod_consensus_decision_frameworks = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing/consensus-decision-frameworks.mdx');
const mod_create_a_pod = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing/create-a-pod.mdx');
const mod_inter_pod_regional_coordination = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing/inter-pod-regional-coordination.mdx');
const mod_managing_meetings_virtual_physical = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing/managing-meetings-virtual-physical.mdx');
const mod_mentoring_new_dispatchers = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing/mentoring-new-dispatchers.mdx');
const mod_training_the_trainers = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing/training-the-trainers.mdx');
const mod_arrest_tracker_jail_support = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/arrest-tracker-jail-support.mdx');
const mod_asl_interpreter_access = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/asl-interpreter-access.mdx');
const mod_bondsman_bail_support = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/bondsman-bail-support.mdx');
const mod_care_station_coordinator = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/care-station-coordinator.mdx');
const mod_child_specialist_safety_care = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/child-specialist-safety-care.mdx');
const mod_child_specialist = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/child-specialist.mdx');
const mod_community_organizer_strategy_impact = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/community-organizer-strategy-impact.mdx');
const mod_court_float_support = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/court-float-support.mdx');
const mod_courthouse_marshal = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/courthouse-marshal.mdx');
const mod_de_escalation_specialist = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/de-escalation-specialist.mdx');
const mod_defensive_presence_nonviolent_shielding = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/defensive-presence-nonviolent-shielding.mdx');
const mod_disability_aid_accessibility = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/disability-aid-accessibility.mdx');
const mod_dispatch_assistant_coordination = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/dispatch-assistant-coordination.mdx');
const mod_docket_tracker = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/docket-tracker.mdx');
const mod_faith_leader_support = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/faith-leader-support.mdx');
const mod_grounding_support = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/grounding-support.mdx');
const mod_immigration_specialist_support = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/immigration-specialist-support.mdx');
const mod_know_your_rights_observer = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/know-your-rights-observer.mdx');
const mod_legal_liaison = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/legal-liaison.mdx');
const mod_legal_observer = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/legal-observer.mdx');
const mod_legal_support_observation_coordination = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/legal-support-observation-coordination.mdx');
const mod_line_scheduler = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/line-scheduler.mdx');
const mod_logistics_support_operations = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/logistics-support-operations.mdx');
const mod_media_press_monitor = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/media-press-monitor.mdx');
const mod_mental_health_support = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/mental-health-support.mdx');
const mod_night_logistics_operations = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/night-logistics-operations.mdx');
const mod_press_coordination = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/press-coordination.mdx');
const mod_resource_drop_coordinator = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/resource-drop-coordinator.mdx');
const mod_runners_and_rides = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/runners-and-rides.mdx');
const mod_safety_marshal_crowd_coordination = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/safety-marshal-crowd-coordination.mdx');
const mod_security_witness = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/security-witness.mdx');
const mod_social_worker_crisis_support = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/social-worker-crisis-support.mdx');
const mod_street_medic_field_support = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/street-medic-field-support.mdx');
const mod_survivor_escort = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/survivor-escort.mdx');
const mod_tech_jammer_counter_surveillance = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/tech-jammer-counter-surveillance.mdx');
const mod_tech_jamming = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/tech-jamming.mdx');
const mod_tech_support_field_systems = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/tech-support-field-systems.mdx');
const mod_translator_language_access = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/translator-language-access.mdx');
const mod_vehicle_support_transport = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/vehicle-support-transport.mdx');
const mod_wellness_float = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/wellness-float.mdx');
const mod_asl_interpreter_micro_badge = () => import('@workspace/ui/data/academy/courses/Standalone_Micro-Badges/asl-interpreter-micro-badge.mdx');
const mod_faith_support_micro_badge = () => import('@workspace/ui/data/academy/courses/Standalone_Micro-Badges/faith-support-micro-badge.mdx');
const mod_survivor_escort_micro_badge = () => import('@workspace/ui/data/academy/courses/Standalone_Micro-Badges/survivor-escort-micro-badge.mdx');
const mod_translator_micro_badge = () => import('@workspace/ui/data/academy/courses/Standalone_Micro-Badges/translator-micro-badge.mdx');
const mod_vehicle_specialist_micro_badge = () => import('@workspace/ui/data/academy/courses/Standalone_Micro-Badges/vehicle-specialist-micro-badge.mdx');
const mod_comms_collapse = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms/comms-collapse.mdx');
const mod_encryption_101 = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms/encryption-101.mdx');
const mod_mesh_networks_hardware_guide = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms/mesh-networks-hardware-guide.mdx');
const mod_mesh_networks_pod_ops = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms/mesh-networks-pod-ops.mdx');
const mod_meshtastic_large_scale = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms/meshtastic-large-scale.mdx');
const mod_proton_secure_communication = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms/proton-secure-communication.mdx');
const mod_abolition_ethics = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/abolition-ethics.mdx');
const mod_community_consent = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/community-consent.mdx');
const mod_decolonization_land_context = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/decolonization-land-context.mdx');
const mod_ethical_dilemmas_mutual_aid = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/ethical-dilemmas-mutual-aid.mdx');
const mod_movement_strategy_escalation_logic = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/movement-strategy-escalation-logic.mdx');
const mod_mutual_aid_history = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/mutual-aid-history.mdx');
const mod_risk_and_responsibility = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/risk-and-responsibility.mdx');
const mod_solidarity_economics_resource_ethics = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/solidarity-economics-resource-ethics.mdx');
const mod_state_corporate_suppression_tactics = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/state-corporate-suppression-tactics.mdx');
const mod__course_template = () => import('@workspace/ui/data/academy/courses/_course-template.mdx');

export type MDXModule = { default: (props: any) => ReactElement };

export const MDX_COURSE_MODULES = {
  'dispatch-coordination': mod_dispatch_coordination,
  'heatmap-verification': mod_heatmap_verification,
  'report-reviewing': mod_report_reviewing,
  'conflict-repair': mod_conflict_repair,
  'mutual-aid-health-wellness': mod_mutual_aid_health_wellness,
  'peer-support-checkins': mod_peer_support_checkins,
  'bystander-support': mod_bystander_support,
  'interacting-with-law-enforcement': mod_interacting_with_law_enforcement,
  'court-support': mod_court_support,
  'jail-support-legal-logistics': mod_jail_support_legal_logistics,
  'understanding-court-support': mod_understanding_court_support,
  'app-free-tactics': mod_app_free_tactics,
  'checkpoint-monitoring': mod_checkpoint_monitoring,
  'digital-resilience-contingency-comms': mod_digital_resilience_contingency_comms,
  'advanced-deescalation': mod_advanced_deescalation,
  'care-support': mod_care_support,
  'collective-safety-protocols': mod_collective_safety_protocols,
  'community-intelligence-situational-reporting': mod_community_intelligence_situational_reporting,
  'crisis-debrief-care': mod_crisis_debrief_care,
  'deescalation-basics': mod_deescalation_basics,
  'environmental-safety': mod_environmental_safety,
  'escalation-evacuation-protocols': mod_escalation_evacuation_protocols,
  'field-safety': mod_field_safety,
  'logistics-resource-management': mod_logistics_resource_management,
  'mass-casualty-response': mod_mass_casualty_response,
  'medical-basics-field-safety': mod_medical_basics_field_safety,
  'national-guard-interactions': mod_national_guard_interactions,
  'otg-checklist': mod_otg_checklist,
  'rapid-field-assessment-triage': mod_rapid_field_assessment_triage,
  'trauma-risk-awareness': mod_trauma_risk_awareness,
  'weapon-safety-firearms-101': mod_weapon_safety_firearms_101,
  'academy-overview': mod_academy_overview,
  'art-watch': mod_art_watch,
  'data-ethics-pledge': mod_data_ethics_pledge,
  'dispatch-training-pathway': mod_dispatch_training_pathway,
  'how-to-report': mod_how_to_report,
  'signal-basics-accessible': mod_signal_basics_accessible,
  'support-art': mod_support_art,
  'why-we-do-this': mod_why_we_do_this,
  'burner-phones-security-culture': mod_burner_phones_security_culture,
  'digital-security-basics': mod_digital_security_basics,
  'intro-to-art': mod_intro_to_art,
  'kyr-basics': mod_kyr_basics,
  'legal-risk-tech': mod_legal_risk_tech,
  'media-awareness-volunteers': mod_media_awareness_volunteers,
  'mental-health-resilience': mod_mental_health_resilience,
  'mesh-networks-intro': mod_mesh_networks_intro,
  'myth-of-total-anonymity': mod_myth_of_total_anonymity,
  'opsec-101': mod_opsec_101,
  'signal-tips': mod_signal_tips,
  'field-role-training-hub': mod_field_role_training_hub,
  'outreach-messaging-community-trust': mod_outreach_messaging_community_trust,
  'responding-to-dispatch-calls': mod_responding_to_dispatch_calls,
  'dealing-with-chaos': mod_dealing_with_chaos,
  'trust-and-ethics-in-dispatch': mod_trust_and_ethics_in_dispatch,
  'admin-tools': mod_admin_tools,
  'cross-zone-coordination': mod_cross_zone_coordination,
  'incident-response-admins': mod_incident_response_admins,
  'regional-data-stewardship': mod_regional_data_stewardship,
  'trust-networks-signature-management': mod_trust_networks_signature_management,
  'zone-administration': mod_zone_administration,
  'zone-lead-overview': mod_zone_lead_overview,
  '60-day-checklist': mod_60_day_checklist,
  '60-day-preparedness': mod_60_day_preparedness,
  'advanced-logistics-resource-planning': mod_advanced_logistics_resource_planning,
  'cdc-location-selection': mod_cdc_location_selection,
  'cdc-logistics-site-operations': mod_cdc_logistics_site_operations,
  'logistics-command-coordination': mod_logistics_command_coordination,
  'supply-chain-resilience': mod_supply_chain_resilience,
  'cross-regional-ethics': mod_cross_regional_ethics,
  'ethical-dilemmas-direct-action': mod_ethical_dilemmas_direct_action,
  'information-ops-counter-propaganda': mod_information_ops_counter_propaganda,
  'movement-strategy-ethics': mod_movement_strategy_ethics,
  'movement-sustainability-legacy': mod_movement_sustainability_legacy,
  'after-action-data-hygiene': mod_after_action_data_hygiene,
  'documentation-safety': mod_documentation_safety,
  'fourth-amendment-rights': mod_fourth_amendment_rights,
  'legal-followthrough-jail-support': mod_legal_followthrough_jail_support,
  'media-disinformation-handling': mod_media_disinformation_handling,
  'visual-alerts': mod_visual_alerts,
  'community-defense-center': mod_community_defense_center,
  'pod-directory': mod_pod_directory,
  'pod-video-content': mod_pod_video_content,
  'radio-communications': mod_radio_communications,
  'consensus-decision-frameworks': mod_consensus_decision_frameworks,
  'create-a-pod': mod_create_a_pod,
  'inter-pod-regional-coordination': mod_inter_pod_regional_coordination,
  'managing-meetings-virtual-physical': mod_managing_meetings_virtual_physical,
  'mentoring-new-dispatchers': mod_mentoring_new_dispatchers,
  'training-the-trainers': mod_training_the_trainers,
  'arrest-tracker-jail-support': mod_arrest_tracker_jail_support,
  'asl-interpreter-access': mod_asl_interpreter_access,
  'bondsman-bail-support': mod_bondsman_bail_support,
  'care-station-coordinator': mod_care_station_coordinator,
  'child-specialist-safety-care': mod_child_specialist_safety_care,
  'child-specialist': mod_child_specialist,
  'community-organizer-strategy-impact': mod_community_organizer_strategy_impact,
  'court-float-support': mod_court_float_support,
  'courthouse-marshal': mod_courthouse_marshal,
  'de-escalation-specialist': mod_de_escalation_specialist,
  'defensive-presence-nonviolent-shielding': mod_defensive_presence_nonviolent_shielding,
  'disability-aid-accessibility': mod_disability_aid_accessibility,
  'dispatch-assistant-coordination': mod_dispatch_assistant_coordination,
  'docket-tracker': mod_docket_tracker,
  'faith-leader-support': mod_faith_leader_support,
  'grounding-support': mod_grounding_support,
  'immigration-specialist-support': mod_immigration_specialist_support,
  'know-your-rights-observer': mod_know_your_rights_observer,
  'legal-liaison': mod_legal_liaison,
  'legal-observer': mod_legal_observer,
  'legal-support-observation-coordination': mod_legal_support_observation_coordination,
  'line-scheduler': mod_line_scheduler,
  'logistics-support-operations': mod_logistics_support_operations,
  'media-press-monitor': mod_media_press_monitor,
  'mental-health-support': mod_mental_health_support,
  'night-logistics-operations': mod_night_logistics_operations,
  'press-coordination': mod_press_coordination,
  'resource-drop-coordinator': mod_resource_drop_coordinator,
  'runners-and-rides': mod_runners_and_rides,
  'safety-marshal-crowd-coordination': mod_safety_marshal_crowd_coordination,
  'security-witness': mod_security_witness,
  'social-worker-crisis-support': mod_social_worker_crisis_support,
  'street-medic-field-support': mod_street_medic_field_support,
  'survivor-escort': mod_survivor_escort,
  'tech-jammer-counter-surveillance': mod_tech_jammer_counter_surveillance,
  'tech-jamming': mod_tech_jamming,
  'tech-support-field-systems': mod_tech_support_field_systems,
  'translator-language-access': mod_translator_language_access,
  'vehicle-support-transport': mod_vehicle_support_transport,
  'wellness-float': mod_wellness_float,
  'asl-interpreter-micro-badge': mod_asl_interpreter_micro_badge,
  'faith-support-micro-badge': mod_faith_support_micro_badge,
  'survivor-escort-micro-badge': mod_survivor_escort_micro_badge,
  'translator-micro-badge': mod_translator_micro_badge,
  'vehicle-specialist-micro-badge': mod_vehicle_specialist_micro_badge,
  'comms-collapse': mod_comms_collapse,
  'encryption-101': mod_encryption_101,
  'mesh-networks-hardware-guide': mod_mesh_networks_hardware_guide,
  'mesh-networks-pod-ops': mod_mesh_networks_pod_ops,
  'meshtastic-large-scale': mod_meshtastic_large_scale,
  'proton-secure-communication': mod_proton_secure_communication,
  'abolition-ethics': mod_abolition_ethics,
  'community-consent': mod_community_consent,
  'decolonization-land-context': mod_decolonization_land_context,
  'ethical-dilemmas-mutual-aid': mod_ethical_dilemmas_mutual_aid,
  'movement-strategy-escalation-logic': mod_movement_strategy_escalation_logic,
  'mutual-aid-history': mod_mutual_aid_history,
  'risk-and-responsibility': mod_risk_and_responsibility,
  'solidarity-economics-resource-ethics': mod_solidarity_economics_resource_ethics,
  'state-corporate-suppression-tactics': mod_state_corporate_suppression_tactics,
  '_course-template': mod__course_template,
} as const satisfies Record<string, () => Promise<MDXModule>>;

export const MDX_COURSE_FRONTMATTER = {
  'dispatch-coordination': {"title":"Dispatch Coordination","slug":"dispatch-coordination","description":"Learn how to coordinate trusted responders using the ART Dispatch system safely and effectively.","type":"qualified","readingTime":35,"version":3},
  'heatmap-verification': {"title":"Heatmap Verification","slug":"heatmap-verification","description":"Learn how to verify and safely publish community reports on the ART heatmap.","type":"qualified","readingTime":15,"version":3},
  'report-reviewing': {"title":"Reviewing ICE Reports","slug":"report-reviewing","description":"Learn how to carefully review and validate ICE-related community reports before publication.","type":"qualified","readingTime":22,"version":3},
  'conflict-repair': {"title":"Conflict Repair & Community Mediation","slug":"conflict-repair","description":"Tools for repairing harm, mediating conflict, and sustaining trust without punishment or expulsion.","type":"qualified","version":1.2,"readingTime":25},
  'mutual-aid-health-wellness': {"title":"Mutual Aid Health & Wellness Logistics","slug":"mutual-aid-health-wellness","description":"Build sustainable support systems for volunteers through rest rotations, nourishment planning, and environmental safety practices.","type":"qualified","version":1.2,"readingTime":25},
  'peer-support-checkins': {"title":"Peer Support & Check-In Circles","slug":"peer-support-checkins","description":"Learn how to run regular, trauma-informed check-ins that keep pods emotionally grounded and connected during ongoing work.","type":"qualified","version":1.3,"readingTime":25},
  'bystander-support': {"title":"Bystander Support Tactics","slug":"bystander-support","description":"Learn safe ways to intervene or support others under threat while minimizing risk and centering community safety.","type":"qualified","readingTime":18,"version":2.5},
  'interacting-with-law-enforcement': {"title":"Interacting with Law Enforcement","slug":"interacting-with-law-enforcement","description":"Stay calm, assert your rights, and support others effectively during encounters with police or ICE.","type":"qualified","readingTime":25,"version":2.4},
  'court-support': {"title":"Court Support Essentials","slug":"court-support","description":"Learn how to safely accompany and support community members during immigration or criminal court proceedings.","type":"qualified","readingTime":30,"version":2.4},
  'jail-support-legal-logistics': {"title":"Jail Support & Legal Logistics","slug":"jail-support-legal-logistics","description":"Coordinate rides, release funds, and secure communication for detained comrades during and after actions.","type":"qualified","version":1.3,"readingTime":28},
  'understanding-court-support': {"title":"Court & Post-Raid Support Coordination","slug":"understanding-court-support","description":"Build systems for post-arrest legal support, community communication, and long-term recovery for affected volunteers and families.","type":"qualified","version":1,"readingTime":25},
  'app-free-tactics': {"title":"App-Free Community Defense Tactics","slug":"app-free-tactics","description":"Learn how to coordinate, communicate, and protect communities without relying on apps, phones, or digital systems.","type":"qualified","readingTime":25,"version":1.3},
  'checkpoint-monitoring': {"title":"Checkpoint Monitoring","slug":"checkpoint-monitoring","description":"Learn how to safely observe and document law enforcement or immigration checkpoints without escalating risk.","type":"qualified","readingTime":30,"version":2.4},
  'digital-resilience-contingency-comms': {"title":"Digital Resilience & Contingency Comms","slug":"digital-resilience-contingency-comms","description":"Learn to maintain communication and coordination when networks fail using mesh, LoRa, radio, and offline protocols.","type":"qualified","version":1.4,"readingTime":18},
  'advanced-deescalation': {"title":"Advanced De-Escalation & Crisis Mediation","slug":"advanced-deescalation","description":"Deepen your de-escalation skills for complex, multi-party, or high-stress situations — including crowd dynamics, trauma-informed responses, and tactical containment under pressure.","type":"qualified","version":1,"readingTime":40},
  'care-support': {"title":"Care & Emotional Support","slug":"care-support","description":"Learn trauma-informed care for crisis situations and peer support within field and mutual aid teams.","type":"qualified","readingTime":35,"version":2.3},
  'collective-safety-protocols': {"title":"Security Protocols for Collective Safety","slug":"collective-safety-protocols","description":"Learn to reduce shared risk through structured roles, exposure limits, and coordinated recovery after leaks or arrests.","type":"qualified","readingTime":30,"version":1.3},
  'community-intelligence-situational-reporting': {"title":"Community Intelligence & Situational Reporting","slug":"community-intelligence-situational-reporting","description":"Learn how to gather, assess, and relay critical on-the-ground information to dispatch teams safely and effectively during community operations.","type":"qualified","readingTime":26,"version":1},
  'crisis-debrief-care': {"title":"Crisis Debriefing & Mutual Care","slug":"crisis-debrief-care","description":"Learn to debrief after difficult actions or trauma and support podmates through recovery, burnout, or breakdown with clarity and consent.","type":"qualified","readingTime":30,"version":1.3},
  'deescalation-basics': {"title":"De-escalation Basics","slug":"deescalation-basics","description":"Learn practical techniques to calm tense situations, preserve dignity, and prevent harm in community or field settings.","type":"qualified","readingTime":40,"version":2.3},
  'environmental-safety': {"title":"Environmental Safety & Extreme Conditions","slug":"environmental-safety","description":"Prepare for heat, cold, smoke, and storms during field or mutual aid operations using low-cost, field-tested safety practices.","type":"qualified","version":1.3,"readingTime":38},
  'escalation-evacuation-protocols': {"title":"Escalation & Evacuation Protocols","slug":"escalation-evacuation-protocols","description":"Learn to anticipate volatile situations and coordinate safe exits, fallback points, and team transport during field operations.","type":"qualified","readingTime":15,"version":1.4},
  'field-safety': {"title":"Field Safety & Situational Awareness","slug":"field-safety","description":"Learn how to stay safe, alert, and coordinated in high-risk field environments through threat recognition, preparation, and team awareness.","type":"qualified","readingTime":35,"version":2.3},
  'logistics-resource-management': {"title":"Logistics & Resource Management","slug":"logistics-resource-management","description":"Learn how to plan, stage, and sustain pods with fuel, supplies, and transport, including resupply and fallback staging for field actions.","type":"qualified","version":1.4,"readingTime":20},
  'mass-casualty-response': {"title":"Mass Casualty Response & Coordination","slug":"mass-casualty-response","description":"Learn how to manage multi-injury emergencies, triage effectively, and coordinate medics, dispatch, and communication under pressure.","type":"qualified","version":1.3,"readingTime":40},
  'medical-basics-field-safety': {"title":"Medical Basics for Field Safety","slug":"medical-basics-field-safety","description":"Learn essential first-aid skills including Stop the Bleed, CPR, and field triage to keep teams safe during actions.","type":"qualified","version":1.4,"readingTime":20},
  'national-guard-interactions': {"title":"Interacting with the National Guard & Active Military Presence","slug":"national-guard-interactions","description":"Learn to recognize, de-escalate, and navigate interactions with National Guard or active-duty forces acting in domestic law enforcement or emergency roles.","type":"qualified","version":1,"readingTime":28},
  'otg-checklist': {"title":"OTG Deployment Checklist & Field Protocols","slug":"otg-checklist","description":"Learn what to do before, during, and after hitting the ground with your pod — using a shared field checklist to stay safe, coordinated, and effective in real time.","type":"qualified","readingTime":15,"version":1.3},
  'rapid-field-assessment-triage': {"title":"Rapid Field Assessment & Triage for Civilian Responders","slug":"rapid-field-assessment-triage","description":"Learn how to quickly and safely assess scenes, prioritize needs, and communicate essential information during emergencies before professional responders arrive.","type":"qualified","readingTime":30,"version":1},
  'trauma-risk-awareness': {"title":"Collective Trauma & Risk Awareness for Frontliners","slug":"trauma-risk-awareness","description":"Learn how to recognize trauma responses, speak up about safety concerns, and build a healthy risk culture that protects both individuals and the community over the long haul.","type":"qualified","readingTime":30,"version":1.2},
  'weapon-safety-firearms-101': {"title":"Weapon Safety & Firearms 101","slug":"weapon-safety-firearms-101","description":"Foundational firearm safety, handling principles, and community risk protocols for field teams operating near or around weapons.","type":"qualified","version":1.2,"readingTime":22},
  'academy-overview': {"title":"ART Academy Overview","slug":"academy-overview","description":"Learn how the ART Academy works, how progress is tracked, and how to get certified for trusted roles.","type":"qualified","readingTime":6,"version":4},
  'art-watch': {"title":"Community Watch Basics","slug":"art-watch","description":"Learn how to identify and safely report harmful state presence using the Community Watch tool.","type":"qualified","readingTime":6,"version":3},
  'data-ethics-pledge': {"title":"ART Data Ethics & Security Pledge","slug":"data-ethics-pledge","description":"A living agreement for anyone handling data or communications in the ART network.","type":"qualified","readingTime":5,"version":2},
  'dispatch-training-pathway': {"title":"ART Dispatch Training Pathway","slug":"dispatch-training-pathway","description":"Understand the training levels required to serve in dispatch and field leadership roles.","type":"overview","readingTime":6,"version":1.3},
  'how-to-report': {"title":"How to Report ICE Presence","slug":"how-to-report","description":"Learn the proper steps to submit a clear, verified Community Watch report safely and effectively.","type":"qualified","readingTime":6,"version":3},
  'signal-basics-accessible': {"title":"Signal Messenger Basics & Accessibility","slug":"signal-basics-accessible","description":"A clear, step-by-step guide to using Signal Messenger — from setup and navigation to calls, muting, and privacy — written for all experience levels, including older or less tech-comfortable users.","type":"qualified","version":1.1,"readingTime":40},
  'support-art': {"title":"Support ART","slug":"support-art","description":"How to sustain ART through community funding and help grow its network of pods, volunteers, and Dispatch Admins.","type":"qualified","readingTime":30,"version":2},
  'why-we-do-this': {"title":"Why We Do This","slug":"why-we-do-this","description":"Understand the moral foundation and historical roots of ART Academy.","type":"qualified","readingTime":6,"version":2},
  'burner-phones-security-culture': {"title":"Burner Phones & Security Culture (2025 Edition)","slug":"burner-phones-security-culture","description":"Learn how to choose, use, and dispose of burner phones safely while embedding them in a broader security culture for protests, cross-border travel, and mutual aid.","type":"qualified","readingTime":15,"version":1.3},
  'digital-security-basics': {"title":"Digital Security Basics","slug":"digital-security-basics","description":"Learn the foundations of secure communication and digital safety in the ART Network.","type":"qualified","readingTime":7,"version":1.3},
  'intro-to-art': {"title":"Introduction to ART Network","slug":"intro-to-art","description":"Learn what ART is, how it works, and the values we operate by.","type":"qualified","readingTime":5,"version":1.3},
  'kyr-basics': {"title":"Know Your Rights Basics","slug":"kyr-basics","description":"Learn the key rights you and your community members have during encounters with ICE or law enforcement.","type":"qualified","readingTime":7,"version":2.5},
  'legal-risk-tech': {"title":"Legal Risk & Tech Use for Activists","slug":"legal-risk-tech","description":"Understand what is protected speech, how digital tools create risk, and how to make informed, collective decisions about app use, organizing, and visibility.","type":"qualified","readingTime":30,"version":1.4},
  'media-awareness-volunteers': {"title":"Media Awareness for Volunteers","slug":"media-awareness-volunteers","description":"Learn how to handle livestreamers, journalists, and public exposure while protecting yourself, your pod, and sensitive information during actions.","type":"qualified","version":1.4,"readingTime":15},
  'mental-health-resilience': {"title":"Mental Health & Resilience Basics","slug":"mental-health-resilience","description":"Learn practical techniques to manage stress, avoid burnout, and build emotional resilience as a volunteer in high-pressure environments.","type":"qualified","version":1.4,"readingTime":15},
  'mesh-networks-intro': {"title":"Intro to Mesh Networks","slug":"mesh-networks-intro","description":"Learn what mesh networks are, why they matter, and how to send your first Meshtastic message.","type":"qualified","version":1.4,"readingTime":18},
  'myth-of-total-anonymity': {"title":"The Myth of Total Anonymity (2025 Reality Check)","slug":"myth-of-total-anonymity","description":"Why total anonymity is nearly impossible in 2025, and how to redirect energy toward realistic security and resilience.","type":"qualified","version":1.4,"readingTime":12},
  'opsec-101': {"title":"Operational Security 101 for Activists and Revolutionaries","slug":"opsec-101","description":"Learn how to identify, assess, and protect sensitive information from state and corporate surveillance using real-world methods adapted for community defense.","type":"qualified","readingTime":30,"version":1.4},
  'signal-tips': {"title":"Secure Messaging with Signal","slug":"signal-tips","description":"Learn how to use Signal for secure communications, with advanced workflows for pods and dispatch operations.","type":"qualified","readingTime":20,"version":1.3},
  'field-role-training-hub': {"title":"Field Role Training Hub","slug":"field-role-training-hub","description":"Overview of core field roles and links to specialized trainings for safe, coordinated action.","type":"qualified","readingTime":10,"version":1.4},
  'outreach-messaging-community-trust': {"title":"Outreach Messaging & Community Trust","slug":"outreach-messaging-community-trust","description":"Learn how to confidently engage businesses and community members about ICE activity, share resources, and build lasting relationships without causing panic.","type":"qualified","readingTime":18,"version":1.4},
  'responding-to-dispatch-calls': {"title":"Responding to Dispatch Calls","slug":"responding-to-dispatch-calls","description":"Learn how to receive, assess, and respond to ART dispatch activations safely and effectively.","type":"qualified","readingTime":8,"version":1.3},
  'dealing-with-chaos': {"title":"Dealing With Chaos","slug":"dealing-with-chaos","description":"Build skills for navigating collapse, lies, escalation, and recovery during live operations.","type":"qualified","readingTime":18,"version":1.3},
  'trust-and-ethics-in-dispatch': {"title":"Trust and Ethics in Dispatch","slug":"trust-and-ethics-in-dispatch","description":"Learn how to make ethically grounded decisions when coordinating field responses and holding movement trust.","type":"qualified","readingTime":25,"version":1.4},
  'admin-tools': {"title":"Admin Tools and Oversight","slug":"admin-tools","description":"Learn how to manage dispatch creation, access roles, and trust signatures in ART Dispatch — with clear boundaries on authority, audits, and accountability.","type":"qualified","readingTime":22,"version":1.4},
  'cross-zone-coordination': {"title":"Cross-Zone Coordination & Global Resilience Planning","slug":"cross-zone-coordination","description":"Learn how to link regional zones, share resources, and maintain operational trust across the decentralized network during crises and large-scale events.","type":"qualified","version":1,"readingTime":28},
  'incident-response-admins': {"title":"Incident Response for Regional Admins","slug":"incident-response-admins","description":"Learn how to coordinate high-risk or sensitive incidents at the regional level while maintaining safety, integrity, and legal protection for all pods.","type":"qualified","version":1.3,"readingTime":40},
  'regional-data-stewardship': {"title":"Regional Data Stewardship & Privacy Oversight","slug":"regional-data-stewardship","description":"Learn how to securely manage volunteer, dispatch, and incident data at the regional level with ethical transparency and legal compliance.","type":"qualified","version":1.3,"readingTime":28},
  'trust-networks-signature-management': {"title":"Trust Networks & Signature Management","slug":"trust-networks-signature-management","description":"Learn to verify, rotate, and audit trust signatures across regional nodes securely and transparently.","type":"qualified","version":1.4,"readingTime":30},
  'zone-administration': {"title":"Strategic Oversight & Zone Administration","slug":"zone-administration","description":"Learn how to manage regional operations, ensure ethical oversight, and maintain resilience across multi-pod or multi-region networks.","type":"qualified","version":1,"readingTime":28},
  'zone-lead-overview': {"title":"Zone Lead & Admin Dispatcher Pathway","slug":"zone-lead-overview","description":"The advanced training path for regional and cross-regional administrators who manage trust, data, and coordination across the Always Ready Tools network.","type":"overview","version":1,"readingTime":10},
  '60-day-checklist': {"title":"60-Day Checklist: Weekly Community Readiness Plan","slug":"60-day-checklist","description":"Build up your pod’s readiness with this step-by-step 8-week preparedness guide for resilient, connected communities.","type":"qualified","readingTime":12,"version":2.2},
  '60-day-preparedness': {"title":"60-Day Preparedness","slug":"60-day-preparedness","description":"A practical, community-first guide for survival, coordination, and dignity when systems fail.","type":"qualified","readingTime":22,"version":2.2},
  'advanced-logistics-resource-planning': {"title":"Advanced Logistics & Resource Planning","slug":"advanced-logistics-resource-planning","description":"Plan, scale, and sustain pod operations for multi-day, multi-pod, or long-term defense with ethical and secure logistics.","type":"qualified","readingTime":18,"version":1.4},
  'cdc-location-selection': {"title":"Choosing Safe & Strategic CDC Locations","slug":"cdc-location-selection","description":"Learn how to choose, assess, and prepare Community Defense Center sites that are accessible, safe, and trusted by the community.","type":"qualified","version":1.1,"readingTime":30},
  'cdc-logistics-site-operations': {"title":"Community Defense Center (CDC) Logistics & Site Operations","slug":"cdc-logistics-site-operations","description":"Learn how to manage supply flow, safety, and communication during active Community Defense Center operations.","type":"qualified","readingTime":30,"version":1},
  'logistics-command-coordination': {"title":"Mutual Aid Logistics Command & Coordination","slug":"logistics-command-coordination","description":"Learn how to organize and synchronize community logistics operations across pods and regions during high-demand or crisis events.","type":"qualified","version":1.1,"readingTime":42},
  'supply-chain-resilience': {"title":"Supply Chain Resilience & Local Production","slug":"supply-chain-resilience","description":"Learn how to secure, localize, and sustain essential supplies for your pod or region when conventional supply chains fail.","type":"qualified","version":1.3,"readingTime":42},
  'cross-regional-ethics': {"title":"Cross-Regional Solidarity & Cultural Ethics","slug":"cross-regional-ethics","description":"Learn how to collaborate across regions and cultures with respect, transparency, and accountability while maintaining decentralized autonomy.","type":"qualified","version":1,"readingTime":26},
  'ethical-dilemmas-direct-action': {"title":"Ethical Dilemmas in Direct Action","slug":"ethical-dilemmas-direct-action","description":"Frameworks for weighing risk, consent, and impact when planning or joining high-risk actions.","type":"qualified","version":1.3,"readingTime":30},
  'information-ops-counter-propaganda': {"title":"Information Operations & Counter-Propaganda for Activists","slug":"information-ops-counter-propaganda","description":"Learn how to recognize, analyze, and counter disinformation and infiltration campaigns targeting activist and mutual aid networks.","type":"qualified","readingTime":28,"version":1.1},
  'movement-strategy-ethics': {"title":"Movement Strategy & Ethics","slug":"movement-strategy-ethics","description":"Learn to design actions, campaigns, and organizing systems guided by shared ethics, sustainability, and strategic foresight.","type":"qualified","version":1,"readingTime":28},
  'movement-sustainability-legacy': {"title":"Long-Term Movement Sustainability & Legacy Planning","slug":"movement-sustainability-legacy","description":"Design strategies that keep movements alive across generations through leadership rotation, cultural preservation, and infrastructure continuity.","type":"qualified","version":1,"readingTime":28},
  'after-action-data-hygiene': {"title":"After-Action Reviews & Data Hygiene","slug":"after-action-data-hygiene","description":"Run secure, structured debriefs and reduce risk by applying strong data hygiene and ethical evidence retention practices.","type":"qualified","readingTime":15,"version":1.4},
  'documentation-safety': {"title":"Documentation & Safety","slug":"documentation-safety","description":"Record incidents safely, legally, and ethically while protecting the people most at risk.","type":"qualified","readingTime":10,"version":2.5},
  'fourth-amendment-rights': {"title":"Understanding Your Fourth Amendment Rights","slug":"fourth-amendment-rights","description":"A crash course on key Supreme Court rulings that shape your right to privacy, search, and seizure — in public, in your car, and beyond.","type":"qualified","readingTime":60,"version":1.3},
  'legal-followthrough-jail-support': {"title":"Legal Follow-Through & Jail Support","slug":"legal-followthrough-jail-support","description":"Coordinate bail, liaise with legal teams, and provide post-arrest support safely — without compromising consent or operational security.","type":"qualified","version":1.4,"readingTime":20},
  'media-disinformation-handling': {"title":"Media and Disinformation Handling","slug":"media-disinformation-handling","description":"Identify, counter, and contain false reports or hostile narratives while maintaining trust and secure, verified communication.","type":"qualified","version":1.4,"readingTime":18},
  'visual-alerts': {"title":"Designing Secure, Visual Alerts","slug":"visual-alerts","description":"Create fast, high-impact alert graphics for Signal or social media that improve response while maintaining operational security.","type":"qualified","readingTime":25,"version":1.2},
  'community-defense-center': {"title":"Deploying a Community Defense Center","slug":"community-defense-center","description":"Learn how to plan, deploy, and operate a flexible Community Defense Center that anchors safety, outreach, and rapid response in your neighborhood.","type":"qualified","readingTime":30,"version":1.4},
  'pod-directory': {"title":"General Pod Directory","slug":"pod-directory","description":"Find regional entry points to connect with local ART pods or start one safely and securely.","type":"qualified","readingTime":12,"version":1.3},
  'pod-video-content': {"title":"Pod Creator Video Content Framework","slug":"pod-video-content","description":"30 modular video ideas to help Pod Creators recruit, educate, and organize safely with trust.","type":"qualified","readingTime":15,"version":1.3},
  'radio-communications': {"title":"Radio Communications & Protocols","slug":"radio-communications","description":"Learn how to use radios for secure, clear, and effective field coordination.","type":"qualified","readingTime":18,"version":1.3},
  'consensus-decision-frameworks': {"title":"Consensus & Rapid Decision Frameworks","slug":"consensus-decision-frameworks","description":"Learn practical methods for making transparent, collective, and time-sensitive decisions without losing trust or momentum.","type":"qualified","version":1.3,"readingTime":38},
  'create-a-pod': {"title":"How to Create a Pod","slug":"create-a-pod","description":"Learn how to start a local response pod in areas without ART coverage.","type":"qualified","readingTime":22,"version":1.3},
  'inter-pod-regional-coordination': {"title":"Inter-Pod & Regional Coordination","slug":"inter-pod-regional-coordination","description":"Learn how to link pods across counties and regions, build fallback mutual aid networks, and coordinate communications during large-scale or multi-day actions.","type":"qualified","readingTime":20,"version":1.4},
  'managing-meetings-virtual-physical': {"title":"Managing and Conducting Meetings (Virtual & Physical)","slug":"managing-meetings-virtual-physical","description":"Learn to plan, facilitate, and secure meetings across digital and physical spaces — balancing structure, inclusion, and situational awareness.","type":"qualified","readingTime":28,"version":1.4},
  'mentoring-new-dispatchers': {"title":"Mentoring New Dispatchers","slug":"mentoring-new-dispatchers","description":"Learn how to guide, train, and support new dispatchers through active mentoring and thoughtful feedback.","type":"qualified","readingTime":17,"version":1.3},
  'training-the-trainers': {"title":"Training the Trainers","slug":"training-the-trainers","description":"Learn how to teach ART Academy material, mentor pod members, and scale knowledge across pods while maintaining consistency and trust.","type":"qualified","readingTime":22,"version":1.3},
  'arrest-tracker-jail-support': {"title":"Arrest Tracker For Detention & Jail Support Coordination","slug":"arrest-tracker-jail-support","description":"Learn how to track arrests and detentions during actions, collect essential information safely, and coordinate with jail support teams for follow-up and release.","type":"qualified","readingTime":60,"version":1},
  'asl-interpreter-access': {"title":"ASL Interpreter For Sign Language Access & Inclusion","slug":"asl-interpreter-access","description":"Learn how to interpret spoken language into American Sign Language (ASL) and vice versa during actions, meetings, and emergencies, ensuring full participation for Deaf and hard-of-hearing community members.","type":"qualified","readingTime":60,"version":1},
  'bondsman-bail-support': {"title":"Bondsman For Bail Coordination & Post-Arrest Support","slug":"bondsman-bail-support","description":"Learn how to coordinate bail, navigate jail procedures, and connect arrestees with legal and community support networks during and after detention.","type":"qualified","readingTime":65,"version":1},
  'care-station-coordinator': {"title":"Care Station Coordinator For Calm Zones, Recovery & Emotional Safety","slug":"care-station-coordinator","description":"Learn how to set up, manage, and sustain quiet or decompression zones during actions and events—creating safe spaces for rest, grounding, and emotional stabilization.","type":"qualified","readingTime":60,"version":1},
  'child-specialist-safety-care': {"title":"Child Specialist For Safety, Care & Emotional Stability for Youth","slug":"child-specialist-safety-care","description":"Learn how to protect, comfort, and stabilize children present or affected during actions, ensuring their physical and emotional safety through trauma-informed, developmentally appropriate care.","type":"qualified","readingTime":60,"version":1},
  'child-specialist': {"title":"Child Specialist Role","slug":"child-specialist","description":"Support children and youth during tense or traumatic situations with trauma-informed, culturally safe, and coordinated care.","type":"qualified","readingTime":48,"version":2.5},
  'community-organizer-strategy-impact': {"title":"Community Organizer For Strategy, Relationship & Long-Term Impact","slug":"community-organizer-strategy-impact","description":"Learn how to connect immediate actions to lasting change through strategic planning, relational organizing, and structured community follow-up.","type":"qualified","readingTime":65,"version":1},
  'court-float-support': {"title":"Court Float Support For Post-Hearing Presence & Gentle Community Care","slug":"court-float-support","description":"Learn to offer calm, compassionate presence outside courthouses after proceedings—supporting impacted individuals and families through grounding, listening, and quiet reassurance.","type":"qualified","readingTime":55,"version":1},
  'courthouse-marshal': {"title":"Courthouse Marshal For Legal Site Coordination & Public Safety Flow","slug":"courthouse-marshal","description":"Learn to manage courthouse surroundings, maintain safety and order, monitor law enforcement behavior, and coordinate with legal observers during hearings or post-arrest support.","type":"qualified","readingTime":65,"version":1},
  'de-escalation-specialist': {"title":"De-escalation Specialist For Preventing Conflict & Promoting Safety","slug":"de-escalation-specialist","description":"Learn trauma-informed and verbal de-escalation techniques to defuse tense situations, reduce harm, and maintain safety during public actions or mutual aid events.","type":"qualified","readingTime":60,"version":1},
  'defensive-presence-nonviolent-shielding': {"title":"Defensive Presence For Visible Protection & Nonviolent Shielding","slug":"defensive-presence-nonviolent-shielding","description":"Learn how to stand as a calm, visible deterrent to violence—protecting vulnerable groups through nonviolent presence, body positioning, and grounded awareness.","type":"qualified","readingTime":60,"version":1},
  'disability-aid-accessibility': {"title":"Disability Aid For Accessibility & Inclusive Field Support","slug":"disability-aid-accessibility","description":"Learn how to assist community members with mobility, sensory, or neurodiverse needs before, during, and after actions using disability justice principles and trauma-informed care.","type":"qualified","readingTime":60,"version":1},
  'dispatch-assistant-coordination': {"title":"Dispatch Assistant For Coordination, Tracking & Communication Support","slug":"dispatch-assistant-coordination","description":"Learn how to assist dispatchers by managing updates, tracking team statuses, and ensuring accurate communication across field and command during operations.","type":"qualified","readingTime":60,"version":1},
  'docket-tracker': {"title":"Docket Tracker For Court Calendar Management & Legal Coordination","slug":"docket-tracker","description":"Learn to track court dockets, hearings, and attendance updates for legal and observer teams—ensuring accurate, timely information flow between field, admin, and defense networks.","type":"qualified","readingTime":55,"version":1},
  'faith-leader-support': {"title":"Faith Leader For Spiritual Grounding & Moral Support in Action","slug":"faith-leader-support","description":"Learn how to provide spiritual, moral, and emotional grounding during actions and crises—supporting teams through reflection, ritual, and presence.","type":"qualified","readingTime":60,"version":1},
  'grounding-support': {"title":"Grounding Support For 1-on-1 Emotional Stabilization & Presence","slug":"grounding-support","description":"Learn to provide calm, trauma-informed, 1-on-1 grounding for people in emotional overwhelm—restoring safety, consent, and self-regulation without escalation or intervention.","type":"qualified","readingTime":55,"version":1},
  'immigration-specialist-support': {"title":"Immigration Specialist For Support, Rights & Rapid Response","slug":"immigration-specialist-support","description":"Learn how to support non-citizens and mixed-status individuals through informed risk assessment, de-escalation, and coordination with trusted legal and advocacy resources.","type":"qualified","readingTime":65,"version":1},
  'know-your-rights-observer': {"title":"Know Your Rights Observer For Accountability & Documentation","slug":"know-your-rights-observer","description":"Learn how to observe and document potential rights violations or misconduct during public actions, ensuring facts are preserved for later accountability and advocacy.","type":"qualified","readingTime":60,"version":1},
  'legal-liaison': {"title":"Legal Liaison For Bridging Field Operations and Legal Defense","slug":"legal-liaison","description":"Learn to coordinate safely and effectively between field teams, dispatch, and legal defense networks, ensuring clear, timely, and secure information flow during legal processes.","type":"qualified","readingTime":65,"version":1},
  'legal-observer': {"title":"Legal Observer Basics","slug":"legal-observer","description":"Learn to document police presence and state behavior safely and credibly during protests or enforcement actions.","type":"qualified","readingTime":17,"version":2.4},
  'legal-support-observation-coordination': {"title":"Legal Support For Observation & Coordination","slug":"legal-support-observation-coordination","description":"Learn how to serve as a legal support volunteer—observing, documenting, and coordinating with legal teams to protect community members’ rights during actions or crises.","type":"qualified","readingTime":60,"version":1},
  'line-scheduler': {"title":"Line Scheduler For Early Arrival & Queue Rotation Coordination","slug":"line-scheduler","description":"Learn how to organize early arrivals, manage queue rotation, and maintain real-time updates for high-demand court appearances with professionalism and care.","type":"qualified","readingTime":55,"version":1},
  'logistics-support-operations': {"title":"Logistics Support For Supply, Setup & Sustenance Operations","slug":"logistics-support-operations","description":"Learn how to organize, manage, and distribute critical supplies like food, water, sanitation, and rest areas during actions, ensuring sustainability and comfort for teams and communities.","type":"qualified","readingTime":60,"version":1},
  'media-press-monitor': {"title":"Media & Press Monitor For Coverage Oversight and Protection","slug":"media-press-monitor","description":"Learn how to engage with journalists and media crews safely, ensuring accurate coverage, respectful boundaries, and protection for vulnerable participants during public actions.","type":"qualified","readingTime":60,"version":1},
  'mental-health-support': {"title":"Mental Health Support For Emotional Care & Trauma Recovery","slug":"mental-health-support","description":"Learn how to provide compassionate, trauma-informed emotional care and grounding to participants during and after actions or crisis events.","type":"qualified","readingTime":60,"version":1},
  'night-logistics-operations': {"title":"Night Logistics For After-Hours Movement & Quiet Coordination","slug":"night-logistics-operations","description":"Learn how to manage nighttime supply runs, quiet movement, and low-visibility coordination with safety, discretion, and precision.","type":"qualified","readingTime":60,"version":1},
  'press-coordination': {"title":"Press Coordination For Media Engagement & Participant Protection","slug":"press-coordination","description":"Learn to coordinate safely and effectively with media, balancing transparency and protection of vulnerable participants during high-visibility actions and events.","type":"qualified","readingTime":65,"version":1},
  'resource-drop-coordinator': {"title":"Resource Drop Coordinator For Contactless Supply Delivery & Field Logistics","slug":"resource-drop-coordinator","description":"Learn how to plan, execute, and confirm contactless resource drop-offs safely and discreetly while maintaining coordination with dispatch and supply networks.","type":"qualified","readingTime":60,"version":1},
  'runners-and-rides': {"title":"Runners & Rides Coordination","slug":"runners-and-rides","description":"Learn to move people, supplies, and information safely through decentralized, low-surveillance methods.","type":"qualified","readingTime":37,"version":2.3},
  'safety-marshal-crowd-coordination': {"title":"Safety Marshal For Crowd Coordination & Hazard Prevention","slug":"safety-marshal-crowd-coordination","description":"Learn how to manage crowd flow, identify hazards, and maintain group cohesion during public actions or mutual aid events while keeping everyone safe and calm.","type":"qualified","readingTime":60,"version":1},
  'security-witness': {"title":"Security Witness For Monitoring Law Enforcement & Institutional Conduct","slug":"security-witness","description":"Learn to observe, record, and report courthouse or law enforcement behavior calmly and accurately, maintaining safety and integrity while documenting potential misconduct.","type":"qualified","readingTime":60,"version":1},
  'social-worker-crisis-support': {"title":"Social Worker For Crisis Care & Resource Navigation","slug":"social-worker-crisis-support","description":"Learn how to provide trauma-informed crisis care, emotional stabilization, and navigation of public or community support systems for individuals impacted during or after actions.","type":"qualified","readingTime":65,"version":1},
  'street-medic-field-support': {"title":"Street Medic For Field First Aid & Trauma Support","slug":"street-medic-field-support","description":"Learn how to provide emergency medical and trauma support during actions, including first aid, chemical exposure response, and psychological stabilization.","type":"qualified","readingTime":60,"version":1},
  'survivor-escort': {"title":"Survivor Escort For Courthouse Navigation & Trauma-Informed Presence","slug":"survivor-escort","description":"Learn to accompany and support survivors or witnesses through courthouse environments with care, consent, and grounded awareness from arrival through exit.","type":"qualified","readingTime":60,"version":1},
  'tech-jammer-counter-surveillance': {"title":"Tech Jammer For Counter-Surveillance & Digital Protection","slug":"tech-jammer-counter-surveillance","description":"Learn how to identify, disrupt, and defend against digital surveillance or tracking attempts while maintaining legal, ethical, and operational safety for community members.","type":"qualified","readingTime":65,"version":1},
  'tech-jamming': {"title":"Tech Jamming & Signal Defense","slug":"tech-jamming","description":"Learn to protect communications, detect surveillance, and defend digital operations without escalation or legal risk.","type":"qualified","readingTime":38,"version":1.2},
  'tech-support-field-systems': {"title":"Tech Support For Field Systems, Security & Comms Maintenance","slug":"tech-support-field-systems","description":"Learn how to configure, maintain, and troubleshoot radios, encrypted devices, livestreams, and communications tools during operations to keep the network online and secure.","type":"qualified","readingTime":60,"version":1},
  'translator-language-access': {"title":"Translator For Language Access & Communication Equity","slug":"translator-language-access","description":"Learn how to provide accurate, ethical, and real-time translation of speech or text during actions, meetings, and dispatch operations to ensure all participants have equal access to information.","type":"qualified","readingTime":60,"version":1},
  'vehicle-support-transport': {"title":"Vehicle Support For Transport, Evacuation & Mobile Safety","slug":"vehicle-support-transport","description":"Learn how to safely transport people, supplies, and teams while navigating dynamic or high-stress environments, ensuring reliable mobility and coordinated exits.","type":"qualified","readingTime":60,"version":1},
  'wellness-float': {"title":"Wellness Float For Mobile Observation & Preventative Care","slug":"wellness-float","description":"Learn how to roam between pods, clusters, or event zones to identify early signs of burnout, distress, or overheating—and provide calm, proactive care before crises occur.","type":"qualified","readingTime":60,"version":1},
  'asl-interpreter-micro-badge': {"title":"ASL Interpreter Micro-Badge","slug":"asl-interpreter-micro-badge","description":"Certification for volunteers fluent in ASL to interpret securely during field actions, legal briefings, and pod coordination.","type":"qualified","readingTime":12,"version":1.4},
  'faith-support-micro-badge': {"title":"Spiritual & Moral Support Micro-Badge","slug":"faith-support-micro-badge","description":"Certification for volunteers who provide calm, grounding, and spiritual or moral support during field actions and recovery, without proselytizing.","type":"qualified","version":1.4,"readingTime":12},
  'survivor-escort-micro-badge': {"title":"Survivor Escort Micro-Badge","slug":"survivor-escort-micro-badge","description":"Certification for volunteers supporting survivors and witnesses through courthouses or stressful public environments with consent, calm, and security awareness.","type":"qualified","version":1.3,"readingTime":14},
  'translator-micro-badge': {"title":"Translator Micro-Badge","slug":"translator-micro-badge","description":"Certification for bilingual or multilingual volunteers providing live translation during field actions, legal work, and coordination while maintaining neutrality and confidentiality.","type":"qualified","version":1.3,"readingTime":14},
  'vehicle-specialist-micro-badge': {"title":"Vehicle Specialist Micro-Badge","slug":"vehicle-specialist-micro-badge","description":"Certification for volunteers maintaining, staging, and operating vehicles for pods and mutual aid missions with safety, security, and reliability.","type":"qualified","version":1.3,"readingTime":14},
  'comms-collapse': {"title":"Comms Collapse Scenarios & Offline Protocols","slug":"comms-collapse","description":"Learn how to operate when Signal fails, the internet is down, or surveillance increases — using radios, runners, fallback sites, and low-tech systems to keep community defense alive.","type":"qualified","version":1.3,"readingTime":32},
  'encryption-101': {"title":"Encryption 101","slug":"encryption-101","description":"Understand how to protect sensitive data using end-to-end encryption, choose strong passphrases, and share securely.","type":"qualified","version":2.3,"readingTime":14},
  'mesh-networks-hardware-guide': {"title":"Mesh Network Hardware & Power Guide","slug":"mesh-networks-hardware-guide","description":"Recommended hardware, antennas, power systems, and accessories for Meshtastic pod and multi-pod operations.","type":"qualified","readingTime":14,"version":1.3},
  'mesh-networks-pod-ops': {"title":"Operating a Pod Mesh Network","slug":"mesh-networks-pod-ops","description":"Learn how to buy, configure, and operate Meshtastic devices for your pod (3–15 nodes) with secure, reliable off-grid communication.","type":"qualified","readingTime":22,"version":1.5},
  'meshtastic-large-scale': {"title":"Meshtastic for Large-Scale Actions","slug":"meshtastic-large-scale","description":"Learn to design, scale, and sustain Meshtastic networks for multi-day or multi-pod actions (15–100+ nodes) while maintaining security and operational resilience.","type":"qualified","readingTime":28,"version":1.5},
  'proton-secure-communication': {"title":"Using Proton for Secure Activism & Communication","slug":"proton-secure-communication","description":"Learn how to use Proton’s privacy tools—Mail, Drive, Calendar, and VPN—to build secure, encrypted workflows for activist, dispatch, and mutual aid operations.","type":"qualified","readingTime":65,"version":1},
  'abolition-ethics': {"title":"Abolition Ethics","slug":"abolition-ethics","description":"Explore the moral framework behind abolitionist resistance and learn to replace punishment with care, repair, and liberation in practice.","type":"qualified","readingTime":18,"version":3.2},
  'community-consent': {"title":"Community Consent","slug":"community-consent","description":"Learn how to respect collective consent, agency, and self-determination in mutual aid, dispatch, and grassroots actions.","type":"qualified","readingTime":65,"version":2.5},
  'decolonization-land-context': {"title":"Decolonization & Land Context","slug":"decolonization-land-context","description":"Understand how colonial histories shape today’s organizing, why land context matters for mutual aid, and how pods can act in material solidarity with Indigenous communities.","type":"qualified","readingTime":15,"version":1.4},
  'ethical-dilemmas-mutual-aid': {"title":"Ethical Dilemmas in Mutual Aid","slug":"ethical-dilemmas-mutual-aid","description":"Explore real-world case studies of difficult decisions pods face, from resource allocation to risk balancing, and practice making values-driven choices under pressure.","type":"qualified","readingTime":18,"version":1.4},
  'movement-strategy-escalation-logic': {"title":"Movement Strategy & Escalation Logic","slug":"movement-strategy-escalation-logic","description":"Learn how to make collective decisions about escalation, de-escalation, and tactics to keep actions aligned with community goals and safety.","type":"qualified","readingTime":20,"version":1.4},
  'mutual-aid-history': {"title":"History of Mutual Aid","slug":"mutual-aid-history","description":"Trace the long tradition of mutual aid in movements for justice and learn how these practices evolved into today’s community defense and care networks.","type":"qualified","readingTime":15,"version":2.4},
  'risk-and-responsibility': {"title":"Risk and Responsibility","slug":"risk-and-responsibility","description":"Learn to assess and manage physical, legal, emotional, and digital risks in collective action to protect your team and sustain long-term resistance.","type":"qualified","readingTime":35,"version":2.2},
  'solidarity-economics-resource-ethics': {"title":"Solidarity Economics & Resource Ethics","slug":"solidarity-economics-resource-ethics","description":"Learn how to fund and sustain pods without compromising autonomy, avoid exploitative funding traps, and build transparent resource-sharing systems.","type":"qualified","readingTime":18,"version":1.3},
  'state-corporate-suppression-tactics': {"title":"Understanding State & Corporate Suppression Tactics","slug":"state-corporate-suppression-tactics","description":"Learn how to recognize state and corporate tactics like infiltration, surveillance, and disinformation, and how to build resilience against them.","type":"qualified","readingTime":20,"version":1.3},
  '_course-template': {"title":"Course Title","slug":"_course-template","description":"1–2 sentence summary of what learners gain.","type":"qualified","readingTime":10,"version":1},
} as const satisfies Record<string, AcademyCourseFrontmatter>;
