// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-academy-mdx-manifest.mjs
/* eslint-disable */

import type { ReactElement } from 'react';
import type { AcademyCourseFrontmatter } from '@workspace/ui/data/academy/types';

const mod_dispatch_coordination = () => import('@workspace/ui/data/academy/courses/Advanced_Tools/dispatch-coordination.mdx');
const mod_heatmap_verification = () => import('@workspace/ui/data/academy/courses/Advanced_Tools/heatmap-verification.mdx');
const mod_report_reviewing = () => import('@workspace/ui/data/academy/courses/Advanced_Tools/report-reviewing.mdx');
const mod_bystander_support = () => import('@workspace/ui/data/academy/courses/Community_Safety___and___Rights/bystander-support.mdx');
const mod_interacting_with_law_enforcement = () => import('@workspace/ui/data/academy/courses/Community_Safety___and___Rights/interacting-with-law-enforcement.mdx');
const mod_court_support = () => import('@workspace/ui/data/academy/courses/Court___and___Post-Raid_Support_Track/court-support.mdx');
const mod_app_free_tactics = () => import('@workspace/ui/data/academy/courses/Direct_Action___and___Protective_Roles_Track/app-free-tactics.mdx');
const mod_checkpoint_monitoring = () => import('@workspace/ui/data/academy/courses/Direct_Action___and___Protective_Roles_Track/checkpoint-monitoring.mdx');
const mod_digital_resilience_contingency_comms = () => import('@workspace/ui/data/academy/courses/Direct_Action___and___Protective_Roles_Track/digital-resilience-contingency-comms.mdx');
const mod_care_support = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/care-support.mdx');
const mod_collective_safety_protocols = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/collective-safety-protocols.mdx');
const mod_crisis_debrief_care = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/crisis-debrief-care.mdx');
const mod_deescalation_basics = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/deescalation-basics.mdx');
const mod_escalation_evacuation_protocols = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/escalation-evacuation-protocols.mdx');
const mod_field_safety = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/field-safety.mdx');
const mod_logistics_resource_management = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/logistics-resource-management.mdx');
const mod_medical_basics_field_safety = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/medical-basics-field-safety.mdx');
const mod_otg_checklist = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/otg-checklist.mdx');
const mod_trauma_risk_awareness = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/trauma-risk-awareness.mdx');
const mod_weapon_safety_firearms_101 = () => import('@workspace/ui/data/academy/courses/Field_Safety___and___Stabilization_Track/weapon-safety-firearms-101.mdx');
const mod_academy_overview = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/academy-overview.mdx');
const mod_art_watch = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/art-watch.mdx');
const mod_data_ethics_pledge = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/data-ethics-pledge.mdx');
const mod_dispatch_training_pathway = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/dispatch-training-pathway.mdx');
const mod_how_to_report = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/how-to-report.mdx');
const mod_support_art = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/support-art.mdx');
const mod_why_we_do_this = () => import('@workspace/ui/data/academy/courses/Getting_Started___lp__Everyone__rp__/why-we-do-this.mdx');
const mod_burner_phones_security_culture = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/burner-phones-security-culture.mdx');
const mod_digital_security_basics = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/digital-security-basics.mdx');
const mod_intro_to_art = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/intro-to-art.mdx');
const mod_kyr_basics = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/kyr-basics.mdx');
const mod_legal_risk_tech = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/legal-risk-tech.mdx');
const mod_media_awareness_volunteers = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/media-awareness-volunteers.mdx');
const mod_mental_health_resilience = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/mental-health-resilience.mdx');
const mod_mesh_networks_intro = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/mesh-networks-intro.mdx');
const mod_myth_of_total_anonymity = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/myth-of-total-anonymity.mdx');
const mod_opsec_101 = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/opsec-101.mdx');
const mod_signal_tips = () => import('@workspace/ui/data/academy/courses/Level_1__c___Team_Member_Onboarding/signal-tips.mdx');
const mod_field_role_training_hub = () => import('@workspace/ui/data/academy/courses/Level_2__c___Field_Coordination_Basics___lp__Basic_Dispatcher__rp__/field-role-training-hub.mdx');
const mod_outreach_messaging_community_trust = () => import('@workspace/ui/data/academy/courses/Level_2__c___Field_Coordination_Basics___lp__Basic_Dispatcher__rp__/outreach-messaging-community-trust.mdx');
const mod_responding_to_dispatch_calls = () => import('@workspace/ui/data/academy/courses/Level_2__c___Field_Coordination_Basics___lp__Basic_Dispatcher__rp__/responding-to-dispatch-calls.mdx');
const mod_dealing_with_chaos = () => import('@workspace/ui/data/academy/courses/Level_3__c___Dispatcher_Certification___lp__Verified_Dispatcher__rp__/dealing-with-chaos.mdx');
const mod_trust_and_ethics_in_dispatch = () => import('@workspace/ui/data/academy/courses/Level_3__c___Dispatcher_Certification___lp__Verified_Dispatcher__rp__/trust-and-ethics-in-dispatch.mdx');
const mod_admin_tools = () => import('@workspace/ui/data/academy/courses/Level_4__c___Zone_Lead___lp__Admin_Dispatcher__rp__/admin-tools.mdx');
const mod_60_day_checklist = () => import('@workspace/ui/data/academy/courses/Logistics___and___Mutual_Aid_Operations_Track/60-day-checklist.mdx');
const mod_60_day_preparedness = () => import('@workspace/ui/data/academy/courses/Logistics___and___Mutual_Aid_Operations_Track/60-day-preparedness.mdx');
const mod_advanced_logistics_resource_planning = () => import('@workspace/ui/data/academy/courses/Logistics___and___Mutual_Aid_Operations_Track/advanced-logistics-resource-planning.mdx');
const mod_after_action_data_hygiene = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal_Track/after-action-data-hygiene.mdx');
const mod_documentation_safety = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal_Track/documentation-safety.mdx');
const mod_fourth_amendment_rights = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal_Track/fourth-amendment-rights.mdx');
const mod_legal_followthrough_jail_support = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal_Track/legal-followthrough-jail-support.mdx');
const mod_media_disinformation_handling = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal_Track/media-disinformation-handling.mdx');
const mod_visual_alerts = () => import('@workspace/ui/data/academy/courses/Observation___and___Legal_Track/visual-alerts.mdx');
const mod_community_defense_center = () => import('@workspace/ui/data/academy/courses/Pod_Creation___and___Regional_Readiness/community-defense-center.mdx');
const mod_pod_directory = () => import('@workspace/ui/data/academy/courses/Pod_Creation___and___Regional_Readiness/pod-directory.mdx');
const mod_pod_video_content = () => import('@workspace/ui/data/academy/courses/Pod_Creation___and___Regional_Readiness/pod-video-content.mdx');
const mod_radio_communications = () => import('@workspace/ui/data/academy/courses/Pod_Creation___and___Regional_Readiness/radio-communications.mdx');
const mod_create_a_pod = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing_Track/create-a-pod.mdx');
const mod_inter_pod_regional_coordination = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing_Track/inter-pod-regional-coordination.mdx');
const mod_managing_meetings_virtual_physical = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing_Track/managing-meetings-virtual-physical.mdx');
const mod_mentoring_new_dispatchers = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing_Track/mentoring-new-dispatchers.mdx');
const mod_training_the_trainers = () => import('@workspace/ui/data/academy/courses/Pod_Leadership___and___Organizing_Track/training-the-trainers.mdx');
const mod_child_specialist = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/child-specialist.mdx');
const mod_legal_observer = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/legal-observer.mdx');
const mod_runners_and_rides = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/runners-and-rides.mdx');
const mod_tech_jamming = () => import('@workspace/ui/data/academy/courses/Specialized_Roles/tech-jamming.mdx');
const mod_asl_interpreter_micro_badge = () => import('@workspace/ui/data/academy/courses/Standalone_Micro-Badges/asl-interpreter-micro-badge.mdx');
const mod_faith_support_micro_badge = () => import('@workspace/ui/data/academy/courses/Standalone_Micro-Badges/faith-support-micro-badge.mdx');
const mod_survivor_escort_micro_badge = () => import('@workspace/ui/data/academy/courses/Standalone_Micro-Badges/survivor-escort-micro-badge.mdx');
const mod_translator_micro_badge = () => import('@workspace/ui/data/academy/courses/Standalone_Micro-Badges/translator-micro-badge.mdx');
const mod_vehicle_specialist_micro_badge = () => import('@workspace/ui/data/academy/courses/Standalone_Micro-Badges/vehicle-specialist-micro-badge.mdx');
const mod_comms_collapse = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms_Track/comms-collapse.mdx');
const mod_encryption_101 = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms_Track/encryption-101.mdx');
const mod_mesh_networks_hardware_guide = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms_Track/mesh-networks-hardware-guide.mdx');
const mod_mesh_networks_pod_ops = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms_Track/mesh-networks-pod-ops.mdx');
const mod_meshtastic_large_scale = () => import('@workspace/ui/data/academy/courses/Tech___and___Comms_Track/meshtastic-large-scale.mdx');
const mod_abolition_ethics = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/abolition-ethics.mdx');
const mod_community_consent = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/community-consent.mdx');
const mod_decolonization_land_context = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/decolonization-land-context.mdx');
const mod_ethical_dilemmas_mutual_aid = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/ethical-dilemmas-mutual-aid.mdx');
const mod_movement_strategy_escalation_logic = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/movement-strategy-escalation-logic.mdx');
const mod_mutual_aid_history = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/mutual-aid-history.mdx');
const mod_risk_and_responsibility = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/risk-and-responsibility.mdx');
const mod_solidarity_economics_resource_ethics = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/solidarity-economics-resource-ethics.mdx');
const mod_state_corporate_suppression_tactics = () => import('@workspace/ui/data/academy/courses/Theory___and___Ethics/state-corporate-suppression-tactics.mdx');
const mod__course_template = () => import('@workspace/ui/data/academy/courses/_course-template.mdx');

export type MDXModule = { default: (props: any) => ReactElement };

export const MDX_COURSE_MODULES = {
  'dispatch-coordination': mod_dispatch_coordination,
  'heatmap-verification': mod_heatmap_verification,
  'report-reviewing': mod_report_reviewing,
  'bystander-support': mod_bystander_support,
  'interacting-with-law-enforcement': mod_interacting_with_law_enforcement,
  'court-support': mod_court_support,
  'app-free-tactics': mod_app_free_tactics,
  'checkpoint-monitoring': mod_checkpoint_monitoring,
  'digital-resilience-contingency-comms': mod_digital_resilience_contingency_comms,
  'care-support': mod_care_support,
  'collective-safety-protocols': mod_collective_safety_protocols,
  'crisis-debrief-care': mod_crisis_debrief_care,
  'deescalation-basics': mod_deescalation_basics,
  'escalation-evacuation-protocols': mod_escalation_evacuation_protocols,
  'field-safety': mod_field_safety,
  'logistics-resource-management': mod_logistics_resource_management,
  'medical-basics-field-safety': mod_medical_basics_field_safety,
  'otg-checklist': mod_otg_checklist,
  'trauma-risk-awareness': mod_trauma_risk_awareness,
  'weapon-safety-firearms-101': mod_weapon_safety_firearms_101,
  'academy-overview': mod_academy_overview,
  'art-watch': mod_art_watch,
  'data-ethics-pledge': mod_data_ethics_pledge,
  'dispatch-training-pathway': mod_dispatch_training_pathway,
  'how-to-report': mod_how_to_report,
  'support-art': mod_support_art,
  'why-we-do-this': mod_why_we_do_this,
  'burner-phones-security-culture': mod_burner_phones_security_culture,
  'digital-security-basics': mod_digital_security_basics,
  'intro-to-art': mod_intro_to_art,
  'kyr-basics': mod_kyr_basics,
  'legal-risk-tech': mod_legal_risk_tech,
  'media-awareness-volunteers': mod_media_awareness_volunteers,
  'mental-health-resilience': mod_mental_health_resilience,
  'mesh-networks-intro': mod_mesh_networks_intro,
  'myth-of-total-anonymity': mod_myth_of_total_anonymity,
  'opsec-101': mod_opsec_101,
  'signal-tips': mod_signal_tips,
  'field-role-training-hub': mod_field_role_training_hub,
  'outreach-messaging-community-trust': mod_outreach_messaging_community_trust,
  'responding-to-dispatch-calls': mod_responding_to_dispatch_calls,
  'dealing-with-chaos': mod_dealing_with_chaos,
  'trust-and-ethics-in-dispatch': mod_trust_and_ethics_in_dispatch,
  'admin-tools': mod_admin_tools,
  '60-day-checklist': mod_60_day_checklist,
  '60-day-preparedness': mod_60_day_preparedness,
  'advanced-logistics-resource-planning': mod_advanced_logistics_resource_planning,
  'after-action-data-hygiene': mod_after_action_data_hygiene,
  'documentation-safety': mod_documentation_safety,
  'fourth-amendment-rights': mod_fourth_amendment_rights,
  'legal-followthrough-jail-support': mod_legal_followthrough_jail_support,
  'media-disinformation-handling': mod_media_disinformation_handling,
  'visual-alerts': mod_visual_alerts,
  'community-defense-center': mod_community_defense_center,
  'pod-directory': mod_pod_directory,
  'pod-video-content': mod_pod_video_content,
  'radio-communications': mod_radio_communications,
  'create-a-pod': mod_create_a_pod,
  'inter-pod-regional-coordination': mod_inter_pod_regional_coordination,
  'managing-meetings-virtual-physical': mod_managing_meetings_virtual_physical,
  'mentoring-new-dispatchers': mod_mentoring_new_dispatchers,
  'training-the-trainers': mod_training_the_trainers,
  'child-specialist': mod_child_specialist,
  'legal-observer': mod_legal_observer,
  'runners-and-rides': mod_runners_and_rides,
  'tech-jamming': mod_tech_jamming,
  'asl-interpreter-micro-badge': mod_asl_interpreter_micro_badge,
  'faith-support-micro-badge': mod_faith_support_micro_badge,
  'survivor-escort-micro-badge': mod_survivor_escort_micro_badge,
  'translator-micro-badge': mod_translator_micro_badge,
  'vehicle-specialist-micro-badge': mod_vehicle_specialist_micro_badge,
  'comms-collapse': mod_comms_collapse,
  'encryption-101': mod_encryption_101,
  'mesh-networks-hardware-guide': mod_mesh_networks_hardware_guide,
  'mesh-networks-pod-ops': mod_mesh_networks_pod_ops,
  'meshtastic-large-scale': mod_meshtastic_large_scale,
  'abolition-ethics': mod_abolition_ethics,
  'community-consent': mod_community_consent,
  'decolonization-land-context': mod_decolonization_land_context,
  'ethical-dilemmas-mutual-aid': mod_ethical_dilemmas_mutual_aid,
  'movement-strategy-escalation-logic': mod_movement_strategy_escalation_logic,
  'mutual-aid-history': mod_mutual_aid_history,
  'risk-and-responsibility': mod_risk_and_responsibility,
  'solidarity-economics-resource-ethics': mod_solidarity_economics_resource_ethics,
  'state-corporate-suppression-tactics': mod_state_corporate_suppression_tactics,
  '_course-template': mod__course_template,
} as const satisfies Record<string, () => Promise<MDXModule>>;

export const MDX_COURSE_FRONTMATTER = {
  'dispatch-coordination': {"title":"Dispatch Coordination","slug":"dispatch-coordination","description":"Coordinate trusted responders using the ART Dispatch system.","type":"qualified","readingTime":35,"version":2.3},
  'heatmap-verification': {"title":"Heatmap Verification","slug":"heatmap-verification","description":"Learn how to verify and publish reports on the ART heatmap.","type":"qualified","readingTime":15,"version":2.2},
  'report-reviewing': {"title":"Reviewing ICE Reports","slug":"report-reviewing","description":"Understand the process of reviewing reports before publication.","type":"qualified","readingTime":22,"version":2.3},
  'bystander-support': {"title":"Bystander Support Tactics","slug":"bystander-support","description":"Learn safe ways to intervene or support others under threat.","type":"qualified","readingTime":18,"version":2.4},
  'interacting-with-law-enforcement': {"title":"Interacting with Law Enforcement","slug":"interacting-with-law-enforcement","description":"Stay calm and effective when dealing with police or ICE.","type":"qualified","readingTime":25,"version":2.3},
  'court-support': {"title":"Court Support Essentials","slug":"court-support","description":"Support community members during immigration or criminal court.","type":"qualified","readingTime":30,"version":2.3},
  'app-free-tactics': {"title":"App-Free Community Defense Tactics","slug":"app-free-tactics","description":"Learn how to show up for your community without relying on phones, apps, or digital tools — using print, in-person, and analogue coordination methods that remain resilient under surveillance or tech failure.","type":"qualified","readingTime":25,"version":1.2},
  'checkpoint-monitoring': {"title":"Checkpoint Monitoring","slug":"checkpoint-monitoring","description":"How to safely observe and document presence at known checkpoints.","type":"qualified","readingTime":30,"version":2.3},
  'digital-resilience-contingency-comms': {"title":"Digital Resilience & Contingency Comms","slug":"digital-resilience-contingency-comms","description":"Learn how to keep communication flowing even when networks fail, using mesh, LoRa, radios, and offline tools to maintain team coordination.","type":"qualified","version":1.3,"readingTime":18},
  'care-support': {"title":"Care & Emotional Support","slug":"care-support","description":"Provide emotional support to affected individuals and teams.","type":"qualified","readingTime":35,"version":2.2},
  'collective-safety-protocols': {"title":"Security Protocols for Collective Safety","slug":"collective-safety-protocols","description":"Learn how to reduce shared risk by establishing safety protocols for pods, dispatchers, and field teams — including role separation, exposure limits, and what to do when things go wrong.","type":"qualified","readingTime":30,"version":1.2},
  'crisis-debrief-care': {"title":"Crisis Debriefing & Mutual Care","slug":"crisis-debrief-care","description":"Learn how to debrief after difficult actions, arrests, exposure, or trauma — and how to support your podmates through breakdown, burnout, or recovery with care, clarity, and boundaries.","type":"qualified","readingTime":30,"version":1.2},
  'deescalation-basics': {"title":"De-escalation Basics","slug":"deescalation-basics","description":"Learn how to calm tense situations and reduce potential harm.","type":"qualified","readingTime":40,"version":2.2},
  'escalation-evacuation-protocols': {"title":"Escalation & Evacuation Protocols","slug":"escalation-evacuation-protocols","description":"Learn how to safely de-escalate volatile situations and coordinate safe exits, fallback points, and transport for your team.","type":"qualified","version":1.3,"readingTime":15},
  'field-safety': {"title":"Field Safety & Situational Awareness","slug":"field-safety","description":"Stay safe and effective in the field during high-risk scenarios.","type":"qualified","readingTime":35,"version":2.2},
  'logistics-resource-management': {"title":"Logistics & Resource Management","slug":"logistics-resource-management","description":"Learn how to plan, stage, and sustain pods with fuel, supplies, and transport, including resupply and fallback staging for field actions.","type":"qualified","version":1.3,"readingTime":20},
  'medical-basics-field-safety': {"title":"Medical Basics for Field Safety","slug":"medical-basics-field-safety","description":"Learn essential first-aid skills including Stop the Bleed, CPR, and field triage to keep teams safe during actions.","type":"qualified","version":1.3,"readingTime":20},
  'otg-checklist': {"title":"OTG Deployment Checklist & Field Protocols","slug":"otg-checklist","description":"Learn what to do before, during, and after hitting the ground with your pod — using a shared field checklist to stay safe, coordinated, and effective in real time.","type":"qualified","readingTime":15,"version":1.2},
  'trauma-risk-awareness': {"title":"Collective Trauma & Risk Awareness for Frontliners","slug":"trauma-risk-awareness","description":"Learn how to recognize trauma responses, speak up about safety concerns, and build a healthy risk culture that protects both individuals and the community over the long haul.","type":"qualified","readingTime":30,"version":1.1},
  'weapon-safety-firearms-101': {"title":"Weapon Safety & Firearms 101","slug":"weapon-safety-firearms-101","description":"Foundational firearm safety, handling principles, and community risk protocols for field teams operating near or around weapons.","type":"qualified","version":1.1,"readingTime":22},
  'academy-overview': {"title":"ART Academy Overview","slug":"academy-overview","description":"Learn how the Academy works and how to get certified.","type":"qualified","readingTime":4,"version":3.1},
  'art-watch': {"title":"Community Watch Basics","slug":"art-watch","description":"Learn how to identify and report harmful state presence (e.g., ICE/CBP/police) using the Community Watch tool.","type":"qualified","readingTime":6,"version":2.4},
  'data-ethics-pledge': {"slug":"data-ethics-pledge","title":"ART Data Ethics & Security Pledge","type":"qualified","readingTime":4,"version":1.3,"description":"A living agreement for anyone handling data or communications in the ART network."},
  'dispatch-training-pathway': {"title":"ART Dispatch Training Pathway","slug":"dispatch-training-pathway","description":"Understand the training levels required to serve in dispatch and field leadership roles.","type":"overview","readingTime":6,"version":1.3},
  'how-to-report': {"title":"How to Report ICE Presence","slug":"how-to-report","description":"Learn the proper steps to submit a clear, verified Community Watch report.","type":"qualified","readingTime":6,"version":2.4},
  'support-art': {"title":"Support ART","slug":"support-art","description":"How to sustain ART through community funding and help grow its network of pods, volunteers, and Dispatch Admins.","type":"qualified","readingTime":30,"version":1.1},
  'why-we-do-this': {"title":"Why We Do This","slug":"why-we-do-this","description":"Understand the roots and moral foundation of ART Academy.","type":"qualified","readingTime":5,"version":1.3},
  'burner-phones-security-culture': {"title":"Burner Phones & Security Culture (2025 Edition)","slug":"burner-phones-security-culture","description":"Learn how to choose, use, and dispose of burner phones safely while embedding them in a broader security culture for protests, cross-border travel, and mutual aid.","type":"qualified","version":1.2,"readingTime":15},
  'digital-security-basics': {"title":"Digital Security Basics","slug":"digital-security-basics","description":"Learn the foundations of secure communication and digital safety in the ART Network.","type":"qualified","readingTime":7,"version":1.2},
  'intro-to-art': {"title":"Introduction to ART Network","slug":"intro-to-art","description":"Learn what ART is, how it works, and the values we operate by.","type":"qualified","readingTime":5,"version":1.2},
  'kyr-basics': {"title":"Know Your Rights Basics","slug":"kyr-basics","description":"Learn the key rights you and your community members have.","type":"qualified","readingTime":7,"version":2.4},
  'legal-risk-tech': {"title":"Legal Risk & Tech Use for Activists","slug":"legal-risk-tech","description":"Understand what is protected speech, how digital tools create risk, and how to make informed, collective decisions about app use, organizing, and visibility.","type":"qualified","readingTime":30,"version":1.3},
  'media-awareness-volunteers': {"title":"Media Awareness for Volunteers","slug":"media-awareness-volunteers","description":"Learn how to handle livestreamers, journalists, and public exposure while protecting yourself, your pod, and sensitive information during actions.","type":"qualified","version":1.3,"readingTime":15},
  'mental-health-resilience': {"title":"Mental Health & Resilience Basics","slug":"mental-health-resilience","description":"Learn practical techniques to manage stress, avoid burnout, and build emotional resilience as a volunteer in high-pressure environments.","type":"qualified","version":1.3,"readingTime":15},
  'mesh-networks-intro': {"title":"Intro to Mesh Networks","slug":"mesh-networks-intro","description":"Learn what mesh networks are, why they matter, and how to send your first Meshtastic message.","type":"qualified","version":1.3,"readingTime":18},
  'myth-of-total-anonymity': {"title":"The Myth of Total Anonymity (2025 Reality Check)","slug":"myth-of-total-anonymity","description":"Why true anonymity at protests or actions is nearly impossible in 2025, and how to redirect energy toward realistic security and resilience.","type":"qualified","version":1.3,"readingTime":12},
  'opsec-101': {"title":"Operational Security 101 for Activists and Revolutionaries","slug":"opsec-101","description":"Learn how to identify, assess, and protect sensitive information from state and corporate surveillance. Based on real-world tactics used by militaries — and repurposed for revolutionaries.","type":"qualified","readingTime":30,"version":1.2},
  'signal-tips': {"title":"Secure Messaging with Signal","slug":"signal-tips","description":"Learn how to use Signal for secure communications, with advanced tricks for pods and dispatch operations.","type":"qualified","readingTime":20,"version":1.1},
  'field-role-training-hub': {"title":"Field Role Training Hub","slug":"field-role-training-hub","description":"Overview of major field roles and links to individual trainings.","type":"qualified","readingTime":10,"version":1.2},
  'outreach-messaging-community-trust': {"title":"Outreach Messaging & Community Trust","slug":"outreach-messaging-community-trust","description":"Learn how to confidently engage businesses and community members about ICE activity, share resources, and build lasting relationships without causing panic.","type":"qualified","version":1.3,"readingTime":18},
  'responding-to-dispatch-calls': {"title":"Responding to Dispatch Calls","slug":"responding-to-dispatch-calls","description":"Learn how to receive, assess, and respond to ART dispatch activations.","type":"qualified","readingTime":8,"version":1.2},
  'dealing-with-chaos': {"title":"Dealing With Chaos","slug":"dealing-with-chaos","description":"Build skills for navigating collapse, lies, escalation, and recovery during live ops.","type":"qualified","readingTime":18,"version":1.2},
  'trust-and-ethics-in-dispatch': {"title":"Trust and Ethics in Dispatch","slug":"trust-and-ethics-in-dispatch","description":"Learn how to make ethically grounded decisions when coordinating field responses.","type":"qualified","readingTime":25,"version":1.1},
  'admin-tools': {"title":"Admin Tools and Oversight","slug":"admin-tools","description":"Learn how to manage dispatch creation, access roles, and trust signatures in ART Dispatch — with clear boundaries on what the tools can (and can’t) do today.","type":"qualified","readingTime":22,"version":1.3},
  '60-day-checklist': {"title":"Weekly Community Readiness Plan","slug":"60-day-checklist","description":"Build up your pod’s readiness with this step-by-step 8-week preparedness guide.","type":"qualified","readingTime":12,"version":2.1},
  '60-day-preparedness': {"title":"60 Day Preparedness","slug":"60-day-preparedness","description":"A practical guide to community survival and coordination when systems break down.","type":"qualified","readingTime":22,"version":2.1},
  'advanced-logistics-resource-planning': {"title":"Advanced Logistics & Resource Planning","slug":"advanced-logistics-resource-planning","description":"Learn how to plan, scale, and sustain pod operations for multi-day actions, multi-pod support, and long-term community defense efforts.","type":"qualified","version":1.3,"readingTime":18},
  'after-action-data-hygiene': {"title":"After-Action Reviews & Data Hygiene","slug":"after-action-data-hygiene","description":"Learn how to run structured debriefs after actions, capture lessons without compromising security, and securely store or destroy sensitive data.","type":"qualified","version":1.3,"readingTime":15},
  'documentation-safety': {"title":"Documentation & Safety","slug":"documentation-safety","description":"Tips for recording safely and securely during incidents.","type":"qualified","readingTime":10,"version":2.4},
  'fourth-amendment-rights': {"title":"Understanding Your Fourth Amendment Rights","slug":"fourth-amendment-rights","description":"A crash course on key Supreme Court rulings shaping your rights in the streets, in your car, at the border, and beyond.","type":"qualified","readingTime":60,"version":1.2},
  'legal-followthrough-jail-support': {"title":"Legal Follow-Through & Jail Support","slug":"legal-followthrough-jail-support","description":"Learn how to coordinate bail, liaise with legal teams, and provide structured post-arrest support without exposing pods to risk.","type":"qualified","version":1.3,"readingTime":20},
  'media-disinformation-handling': {"title":"Media and Disinformation Handling","slug":"media-disinformation-handling","description":"Learn how to identify, counter, and contain false reports and hostile narratives while coordinating accurate information flow with pods and the public.","type":"qualified","version":1.3,"readingTime":18},
  'visual-alerts': {"title":"Designing Secure, Visual Alerts","slug":"visual-alerts","description":"Learn how to create fast, high-impact alert graphics for Signal or social media that improve action response and reinforce operational security.","type":"qualified","readingTime":25,"version":1.1},
  'community-defense-center': {"title":"Deploying a Community Defense Center","slug":"community-defense-center","description":"Learn how to set up and operate a flexible, mobile Community Defense Center to support rapid response and public safety.","type":"qualified","readingTime":30,"version":1.3},
  'pod-directory': {"title":"General Pod Directory","slug":"pod-directory","description":"Find regional entry points to connect with local ART pods or start one.","type":"qualified","version":1.2,"readingTime":12},
  'pod-video-content': {"title":"Pod Creator Video Content Framework","slug":"pod-video-content","description":"30 flexible video ideas to help new Pod Creators recruit, educate, and organize with trust.","type":"qualified","version":1.2,"readingTime":15},
  'radio-communications': {"title":"Radio Communications & Protocols","slug":"radio-communications","description":"Learn how to use radios for secure, clear, and effective field coordination.","type":"qualified","readingTime":15,"version":1.2},
  'create-a-pod': {"title":"How to Create a Pod","slug":"create-a-pod","description":"Learn how to start a local response pod in areas without ART coverage.","type":"qualified","readingTime":20,"version":1.2},
  'inter-pod-regional-coordination': {"title":"Inter-Pod & Regional Coordination","slug":"inter-pod-regional-coordination","description":"Learn how to link pods across counties and regions, build fallback mutual aid networks, and coordinate communications during large-scale or multi-day actions.","type":"qualified","version":1.3,"readingTime":18},
  'managing-meetings-virtual-physical': {"title":"Managing and Conducting Meetings (Virtual & Physical)","slug":"managing-meetings-virtual-physical","description":"Learn to plan, facilitate, and secure meetings across digital and physical spaces — balancing structure, inclusion, and situational awareness.","type":"qualified","version":1.3,"readingTime":26},
  'mentoring-new-dispatchers': {"title":"Mentoring New Dispatchers","slug":"mentoring-new-dispatchers","description":"Learn how to guide, train, and support new dispatchers through active mentoring and thoughtful feedback.","type":"qualified","readingTime":15,"version":1.2},
  'training-the-trainers': {"title":"Training the Trainers","slug":"training-the-trainers","description":"Learn how to teach ART Academy material, mentor pod members, and scale knowledge across pods while maintaining consistency and trust.","type":"qualified","version":1.2,"readingTime":20},
  'child-specialist': {"title":"Child Specialist Role","slug":"child-specialist","description":"Support children and youth during tense or traumatic situations.","type":"qualified","readingTime":45,"version":2.4},
  'legal-observer': {"title":"Legal Observer Basics","slug":"legal-observer","description":"Learn how to document police presence in a legal observer role.","type":"qualified","readingTime":15,"version":2.3},
  'runners-and-rides': {"title":"Runners & Rides Coordination","slug":"runners-and-rides","description":"How to move people, supplies, and information securely.","type":"qualified","readingTime":35,"version":2.2},
  'tech-jamming': {"title":"Tech Jamming & Signal Defense","slug":"tech-jamming","description":"Use technology to protect communication and disrupt surveillance.","type":"qualified","readingTime":35,"version":1.1},
  'asl-interpreter-micro-badge': {"title":"ASL Interpreter Micro-Badge","slug":"asl-interpreter-micro-badge","description":"Certification for volunteers fluent in American Sign Language to interpret during field actions, court support, and pod coordination.","type":"qualified","version":1.3,"readingTime":10},
  'faith-support-micro-badge': {"title":"Spiritual & Moral Support Micro-Badge","slug":"faith-support-micro-badge","description":"Certification for volunteers who provide non-denominational grounding, spiritual comfort, or trusted moral presence during field actions and recovery, without proselytizing.","type":"qualified","version":1.3,"readingTime":10},
  'survivor-escort-micro-badge': {"title":"Survivor Escort Micro-Badge","slug":"survivor-escort-micro-badge","description":"Certification for volunteers supporting survivors and witnesses as they navigate courthouses, legal processes, or high-stress public spaces.","type":"qualified","version":1.2,"readingTime":12},
  'translator-micro-badge': {"title":"Translator Micro-Badge","slug":"translator-micro-badge","description":"Certification for bilingual or multilingual volunteers providing live translation during field actions, court support, or pod coordination.","type":"qualified","version":1.2,"readingTime":12},
  'vehicle-specialist-micro-badge': {"title":"Vehicle Specialist Micro-Badge","slug":"vehicle-specialist-micro-badge","description":"Certification for volunteers responsible for driving, staging, and supporting pod operations with reliable vehicles during actions and mutual aid efforts.","type":"qualified","version":1.2,"readingTime":12},
  'comms-collapse': {"title":"Comms Collapse Scenarios & Offline Protocols","slug":"comms-collapse","description":"Learn how to operate when Signal fails, the internet is down, or surveillance increases — using radios, runners, fallback sites, and low-tech systems to keep community defense alive.","type":"qualified","readingTime":30,"version":1.2},
  'encryption-101': {"title":"Encryption 101","slug":"encryption-101","description":"Understand how data is protected and how to use end-to-end encryption.","type":"qualified","readingTime":12,"version":2.2},
  'mesh-networks-hardware-guide': {"title":"Mesh Network Hardware & Power Guide","slug":"mesh-networks-hardware-guide","description":"Recommended hardware, antennas, power systems, and accessories for Meshtastic pod and multi-pod operations.","type":"appendix","version":1.2,"readingTime":14},
  'mesh-networks-pod-ops': {"title":"Operating a Pod Mesh Network","slug":"mesh-networks-pod-ops","description":"Learn how to buy, configure, and operate Meshtastic devices for your pod (3–15 nodes).","type":"qualified","version":1.4,"readingTime":22},
  'meshtastic-large-scale': {"title":"Meshtastic for Large-Scale Actions","slug":"meshtastic-large-scale","description":"Learn to design, scale, and sustain Meshtastic networks for multi-day or multi-pod actions (15–100+ nodes).","type":"qualified","version":1.4,"readingTime":28},
  'abolition-ethics': {"title":"Abolition Ethics","slug":"abolition-ethics","description":"Explore the moral framework behind abolitionist resistance.","type":"qualified","readingTime":18,"version":3.1},
  'community-consent': {"title":"Community Consent","slug":"community-consent","description":"Learn how to respect consent and agency when taking action.","type":"qualified","readingTime":65,"version":2.4},
  'decolonization-land-context': {"title":"Decolonization & Land Context","slug":"decolonization-land-context","description":"Learn how colonial histories shape our present, why land context matters for mutual aid, and how pods can act in solidarity with Indigenous communities.","type":"qualified","version":1.3,"readingTime":15},
  'ethical-dilemmas-mutual-aid': {"title":"Ethical Dilemmas in Mutual Aid","slug":"ethical-dilemmas-mutual-aid","description":"Explore real-world case studies of difficult decisions pods face, from resource allocation to risk balancing, and practice making values-driven choices under pressure.","type":"qualified","version":1.3,"readingTime":18},
  'movement-strategy-escalation-logic': {"title":"Movement Strategy & Escalation Logic","slug":"movement-strategy-escalation-logic","description":"Learn how to make collective decisions about escalation, de-escalation, and tactics to keep actions aligned with community goals and safety.","type":"qualified","version":1.3,"readingTime":20},
  'mutual-aid-history': {"title":"History of Mutual Aid","slug":"mutual-aid-history","description":"Trace the long tradition of mutual aid in movements for justice.","type":"qualified","readingTime":15,"version":2.3},
  'risk-and-responsibility': {"title":"Risk and Responsibility","slug":"risk-and-responsibility","description":"Understand the risks involved and how to prepare.","type":"qualified","readingTime":35,"version":2.1},
  'solidarity-economics-resource-ethics': {"title":"Solidarity Economics & Resource Ethics","slug":"solidarity-economics-resource-ethics","description":"Learn how to fund and sustain pods without compromising autonomy, avoid exploitative funding traps, and build transparent resource-sharing systems.","type":"qualified","version":1.2,"readingTime":18},
  'state-corporate-suppression-tactics': {"title":"Understanding State & Corporate Suppression Tactics","slug":"state-corporate-suppression-tactics","description":"Learn how to recognize state and corporate tactics like infiltration, surveillance, and disinformation, and how to build resilience against them.","type":"qualified","version":1.2,"readingTime":20},
  '_course-template': {"title":"Course Title","slug":"_course-template","description":"1–2 sentence summary of what learners gain.","type":"qualified","readingTime":10,"version":1},
} as const satisfies Record<string, AcademyCourseFrontmatter>;
