-- Notifications schema for Supabase (durable + realtime-ready)
-- Safe to re-run (IF NOT EXISTS used throughout)

-- Ensure gen_random_uuid() is available
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_net;
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Enum for levels (matches UI: info | success | warning | error)
DO $$ BEGIN
  CREATE TYPE public.notification_level AS ENUM ('info','success','warning','error');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Core notifications table (one row per message)
CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel TEXT NOT NULL DEFAULT 'system',
  title TEXT NOT NULL,
  body TEXT,
  level public.notification_level NOT NULL DEFAULT 'info',
  link TEXT,
  sticky BOOLEAN NOT NULL DEFAULT FALSE,
  meta JSONB, -- e.g. { "icon": "/icon-192.png" }
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id)
);

-- Recipients join (one row per user targeted)
CREATE TABLE IF NOT EXISTS public.notification_recipients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id UUID NOT NULL REFERENCES public.notifications(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  read_at TIMESTAMPTZ,
  dismissed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (notification_id, user_id)
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_expires_at ON public.notifications (expires_at);
CREATE INDEX IF NOT EXISTS idx_notification_recipients_user ON public.notification_recipients (user_id, read_at, dismissed_at);

-- Realtime friendliness (optional but nice to have when updating rows)
ALTER TABLE public.notifications REPLICA IDENTITY FULL;
ALTER TABLE public.notification_recipients REPLICA IDENTITY FULL;

-- RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_recipients ENABLE ROW LEVEL SECURITY;

-- Only allow a user to see notifications that were targeted to them and not dismissed
DROP POLICY IF EXISTS notifications_select_for_recipient ON public.notifications;
CREATE POLICY notifications_select_for_recipient ON public.notifications
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.notification_recipients nr
    WHERE nr.notification_id = public.notifications.id
      AND nr.user_id = auth.uid()
      AND (nr.dismissed_at IS NULL)
  )
);

-- Default: Do NOT allow arbitrary inserts/updates/deletes on notifications from client
-- Use service role keys or serverless functions to create notifications.

-- Grants (required alongside RLS policies)
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON TABLE public.notifications TO authenticated;
GRANT SELECT, UPDATE ON TABLE public.notification_recipients TO authenticated;

-- Recipients policies: users can see and update only their own recipient rows
DROP POLICY IF EXISTS recipients_select_own ON public.notification_recipients;
CREATE POLICY recipients_select_own ON public.notification_recipients
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS recipients_update_own ON public.notification_recipients;
CREATE POLICY recipients_update_own ON public.notification_recipients
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- No client insert/delete on recipients by default (service role only)

-- Optional view for convenience (current user's notifications + recipient state)
DROP VIEW IF EXISTS public.user_notifications;
CREATE VIEW public.user_notifications AS
SELECT
  nr.user_id,
  n.id AS notification_id,
  n.channel,
  n.title,
  n.body,
  n.level,
  n.link,
  n.sticky,
  n.meta,
  n.created_at,
  n.expires_at,
  nr.read_at,
  nr.dismissed_at
FROM public.notification_recipients nr
JOIN public.notifications n ON n.id = nr.notification_id;

COMMENT ON VIEW public.user_notifications IS 'Join of notifications and recipient state; RLS on underlying tables still applies. Filter by user_id = auth.uid() on the client or add a SECURITY INVOKER wrapper.';

GRANT SELECT ON public.user_notifications TO authenticated;

-- Helper RPCs (optional): consumer-friendly read/dismiss for current user
-- Drop first to allow changing return type idempotently
DROP FUNCTION IF EXISTS public.mark_notification_read(UUID);
CREATE OR REPLACE FUNCTION public.mark_notification_read(p_notification_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_count INTEGER := 0;
BEGIN
  UPDATE public.notification_recipients
    SET read_at = COALESCE(read_at, now())
  WHERE notification_id = p_notification_id AND user_id = auth.uid();
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END $$;

GRANT EXECUTE ON FUNCTION public.mark_notification_read(UUID) TO authenticated;

-- Drop first to allow changing return type idempotently
DROP FUNCTION IF EXISTS public.dismiss_notification(UUID);
CREATE OR REPLACE FUNCTION public.dismiss_notification(p_notification_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_count INTEGER := 0;
BEGIN
  UPDATE public.notification_recipients
    SET dismissed_at = now()
  WHERE notification_id = p_notification_id AND user_id = auth.uid();
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END $$;

GRANT EXECUTE ON FUNCTION public.dismiss_notification(UUID) TO authenticated;

-- Helper RPC (server-side use): create a notification and target specific users
-- NOTE: This should be called with service role key or via a secured edge function.
CREATE OR REPLACE FUNCTION public.create_notification_for_users(
  p_title TEXT,
  p_user_ids UUID[],
  p_body TEXT DEFAULT NULL,
  p_level public.notification_level DEFAULT 'info',
  p_channel TEXT DEFAULT 'system',
  p_link TEXT DEFAULT NULL,
  p_sticky BOOLEAN DEFAULT FALSE,
  p_expires_at TIMESTAMPTZ DEFAULT NULL,
  p_meta JSONB DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id UUID;
BEGIN
  INSERT INTO public.notifications (title, body, level, channel, link, sticky, expires_at, meta, created_by)
  VALUES (p_title, p_body, p_level, p_channel, p_link, p_sticky, p_expires_at, p_meta, auth.uid())
  RETURNING id INTO v_id;

  INSERT INTO public.notification_recipients (notification_id, user_id)
  SELECT v_id, uid FROM UNNEST(p_user_ids) AS uid
  ON CONFLICT (notification_id, user_id) DO NOTHING;

  RETURN v_id;
END $$;

COMMENT ON FUNCTION public.create_notification_for_users IS 'Service function: creates a notification and assigns recipients. Call with service role or secure via RLS.';
-- Preferences table: opt-out and channel mutes
CREATE TABLE IF NOT EXISTS public.notification_prefs (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  global_opt_out BOOLEAN NOT NULL DEFAULT FALSE,
  muted_channels TEXT[] NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.notification_prefs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS notification_prefs_select_own ON public.notification_prefs;
CREATE POLICY notification_prefs_select_own ON public.notification_prefs
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS notification_prefs_upsert_own ON public.notification_prefs;
CREATE POLICY notification_prefs_upsert_own ON public.notification_prefs
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS notification_prefs_update_own ON public.notification_prefs;
CREATE POLICY notification_prefs_update_own ON public.notification_prefs
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

GRANT SELECT, INSERT, UPDATE ON public.notification_prefs TO authenticated;

-- =========================================================
-- Cron Job for Push Worker (Optional)
-- Requires pg_cron and pg_net extensions.
-- Replace [PROJECT_REF] and [SERVICE_ROLE_KEY] with your actual values.
-- =========================================================
/*
SELECT cron.schedule(
  'push-notifications-schedule',
  '*/1 * * * *',
  $$
  SELECT net.http_post(
      url := 'https://[PROJECT_REF].supabase.co/functions/v1/bright-processor',
      body := '{}'::jsonb,
      headers := '{"Content-Type": "application/json", "Authorization": "Bearer [SERVICE_ROLE_KEY]"}'::jsonb
  ) as request_id;
  $$
);
*/
