export const US_STATES = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
];

export const STATE_TIMEZONES: Record<string, string> = {
  // Pacific Time
  WA: 'America/Los_Angeles',
  OR: 'America/Los_Angeles',
  CA: 'America/Los_Angeles',
  NV: 'America/Los_Angeles',

  // Mountain Time (no DST in AZ)
  AZ: 'America/Phoenix',
  MT: 'America/Denver',
  UT: 'America/Denver',
  CO: 'America/Denver',
  NM: 'America/Denver',
  WY: 'America/Denver',
  ID: 'America/Boise',

  // Central Time
  TX: 'America/Chicago',
  OK: 'America/Chicago',
  KS: 'America/Chicago',
  NE: 'America/Chicago',
  SD: 'America/Chicago',
  ND: 'America/Chicago',
  MN: 'America/Chicago',
  IA: 'America/Chicago',
  MO: 'America/Chicago',
  WI: 'America/Chicago',
  IL: 'America/Chicago',
  AR: 'America/Chicago',
  LA: 'America/Chicago',
  MS: 'America/Chicago',
  AL: 'America/Chicago',
  TN: 'America/Chicago' /* Note: split state, but defaulting to Central */,
  KY: 'America/Chicago' /* Also split, default to Central */,

  // Eastern Time
  FL: 'America/New_York',
  GA: 'America/New_York',
  SC: 'America/New_York',
  NC: 'America/New_York',
  VA: 'America/New_York',
  DC: 'America/New_York',
  MD: 'America/New_York',
  DE: 'America/New_York',
  PA: 'America/New_York',
  NJ: 'America/New_York',
  NY: 'America/New_York',
  CT: 'America/New_York',
  RI: 'America/New_York',
  MA: 'America/New_York',
  VT: 'America/New_York',
  NH: 'America/New_York',
  ME: 'America/New_York',
  OH: 'America/New_York',
  IN: 'America/New_York',
  MI: 'America/New_York',
  WV: 'America/New_York',

  // Alaska & Hawaii
  AK: 'America/Anchorage',
  HI: 'Pacific/Honolulu',
};

export const US_TIMEZONES = ['Pacific', 'Mountain', 'Central', 'Eastern', 'Alaska', 'Hawaii'];
